name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🔨 Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'
  - title: '🎨 Styling'
    labels:
      - 'style'
      - 'styles'
  - title: '✅ Tests'
    labels:
      - 'test'
      - 'testing'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Installation
  Download the appropriate installer for your operating system:
  - Windows: CardMind-Setup.exe
  - macOS: CardMind.dmg
  - Linux: CardMind.AppImage

  ## Thank You
  Thank you to all our contributors who helped make this release possible!
