version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cardmind
      POSTGRES_USER: cardmind
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cardmind"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: alexcdever/cardmind-server:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEPLOYMENT_MODE=web
      - DATABASE_URL=postgres://cardmind:${DB_PASSWORD:-changeme}@db:5432/cardmind
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3001}
      - RUST_LOG=info
    ports:
      - "3002:3002"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: alexcdever/cardmind-web:latest
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:3002}
    ports:
      - "3001:80"
    depends_on:
      server:
        condition: service_healthy

volumes:
  postgres_data:
