// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

/// # 卡片模型
///
/// 定义 CardMind 中的卡片实体数据结构。
/// 包含卡片的基本属性：ID、标题、内容、时间戳和删除标记。
library card;

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// 卡片实体
class Card {
  /// 卡片 ID（UUID v7）
  final UuidValue id;

  /// 卡片标题
  final String title;

  /// 卡片正文（Markdown）
  final String content;

  /// 创建时间（秒）
  final PlatformInt64 createdAt;

  /// 更新时间（秒）
  final PlatformInt64 updatedAt;

  /// 软删除标记
  final bool deleted;

  /// 创建 Card 实例
  const Card({
    required this.id,
    required this.title,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
    required this.deleted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Card &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          content == other.content &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deleted == other.deleted;
}
