// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'discovery.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store.dart';
import 'sync.dart';

/// 创建同步服务
Future<SyncService> createSyncService() =>
    RustLib.instance.api.crateApiCreateSyncService();

/// 将所有 CRDT 笔记同步到 SQLite 存储
Future<void> syncNotesToStore({
  required SyncService svc,
  required NoteStore store,
}) => RustLib.instance.api.crateApiSyncNotesToStore(svc: svc, store: store);

/// 创建笔记
Future<void> noteCreate({
  required SyncService svc,
  required String id,
  required String content,
}) =>
    RustLib.instance.api.crateApiNoteCreate(svc: svc, id: id, content: content);

/// 读取笔记内容
Future<String?> noteGet({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNoteGet(svc: svc, id: id);

/// 导出所有笔记的序列化快照
Future<Uint8List> noteExportAll({required SyncService svc}) =>
    RustLib.instance.api.crateApiNoteExportAll(svc: svc);

/// 导入快照
Future<void> noteImportAll({
  required SyncService svc,
  required List<int> data,
}) => RustLib.instance.api.crateApiNoteImportAll(svc: svc, data: data);

/// 推送到对端
Future<void> pushToPeer({
  required SyncService svc,
  required String peerId,
  required List<String> ips,
}) =>
    RustLib.instance.api.crateApiPushToPeer(svc: svc, peerId: peerId, ips: ips);

/// 接受对端推送
Future<Uint8List> acceptPush({required SyncService svc}) =>
    RustLib.instance.api.crateApiAcceptPush(svc: svc);

/// 设备发现 — 广播本设备
Future<void> startAdvertising({
  required DiscoveryService disc,
  required String deviceId,
  required int port,
}) => RustLib.instance.api.crateApiStartAdvertising(
  disc: disc,
  deviceId: deviceId,
  port: port,
);

/// 设备发现 — 扫描对端
Future<List<PeerInfo>> discoverPeers({required DiscoveryService disc}) =>
    RustLib.instance.api.crateApiDiscoverPeers(disc: disc);

/// 创建 SQLite 存储
Future<NoteStore> createNoteStore({required String path}) =>
    RustLib.instance.api.crateApiCreateNoteStore(path: path);

/// SQLite — 列出所有笔记
Future<List<NoteRow>> storeList({required NoteStore store}) =>
    RustLib.instance.api.crateApiStoreList(store: store);

/// SQLite — 搜索笔记
Future<List<NoteRow>> storeSearch({
  required NoteStore store,
  required String query,
}) => RustLib.instance.api.crateApiStoreSearch(store: store, query: query);
