// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'discovery.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store.dart';
import 'sync.dart';

/// 创建同步服务
Future<SyncService> createSyncService() =>
    RustLib.instance.api.crateApiCreateSyncService();

/// 创建绑定数据目录的持久化同步服务。
Future<SyncService> createPersistentSyncService({required String path}) =>
    RustLib.instance.api.crateApiCreatePersistentSyncService(path: path);

/// 获取本设备 iroh 身份 ID（SecretKey 持久化后跨重启稳定）。
Future<String> getDeviceId({required SyncService svc}) =>
    RustLib.instance.api.crateApiGetDeviceId(svc: svc);

/// 获取本设备名（配对握手时发送给对端）。
Future<String> getDeviceName({required SyncService svc}) =>
    RustLib.instance.api.crateApiGetDeviceName(svc: svc);

/// 设置本设备名。
Future<void> setDeviceName({required SyncService svc, required String name}) =>
    RustLib.instance.api.crateApiSetDeviceName(svc: svc, name: name);

/// 本端点当前绑定的 IPv4 地址列表（"ip:port"，配对目标/mDNS 广播用）。
Future<List<String>> localAddrs({required SyncService svc}) =>
    RustLib.instance.api.crateApiLocalAddrs(svc: svc);

/// 配对 — 确认方：生成 6 位数字配对码（密码学随机，10 分钟有效）。返回码。
Future<String> beginPairingAccept({required SyncService svc}) =>
    RustLib.instance.api.crateApiBeginPairingAccept(svc: svc);

/// 配对 — 确认方：生成配对码并启动 mDNS 广播（任务 J 组合 API）。
///
/// 码与广播在同一调用内完成（保证配对期间广播一定在）；port 用本端点实际
/// 监听端口。配对结束（弹窗关闭/完成/取消）时调用 [`stop_pairing_advertising`]。
Future<String> beginPairingAcceptWithAdvertising({required SyncService svc}) =>
    RustLib.instance.api.crateApiBeginPairingAcceptWithAdvertising(svc: svc);

/// 配对 — 停止 mDNS 广播（幂等；配对弹窗关闭/完成/取消时调用）。
Future<void> stopPairingAdvertising({required SyncService svc}) =>
    RustLib.instance.api.crateApiStopPairingAdvertising(svc: svc);

/// 设备发现 — 经 SyncService 扫描对端（任务 J：发起方设备 ID 留空时自动填充）。
Future<List<PeerInfo>> syncDiscoverPeers({required SyncService svc}) =>
    RustLib.instance.api.crateApiSyncDiscoverPeers(svc: svc);

/// 配对 — 确认方：阻塞接收发起方的配对请求（等待发起方连接）。
///
/// 等待期间抢到的推送帧会立即导入（不丢失），随后继续等待配对请求。
Future<PairingRequest> acceptPairingRequest({required SyncService svc}) =>
    RustLib.instance.api.crateApiAcceptPairingRequest(svc: svc);

/// 配对 — 确认方：在 [timeout] 内接收发起方配对请求（**有界等待**；超时返回 None）。
///
/// 任务 M 决策点 1 的落点：FRB opaque 上的阻塞等待无法安全取消，必须有界——
/// UI 侧显示码流程以短窗口（10s）轮询调用本方法，弹窗关闭/取消后等待任务在
/// 窗口内释放，不留下永久阻塞任务（设计目标 5）。总时限由 Flutter 侧控制。
Future<PairingRequest?> acceptPairingRequestWithTimeout({
  required SyncService svc,
  required Duration timeout,
}) => RustLib.instance.api.crateApiAcceptPairingRequestWithTimeout(
  svc: svc,
  timeout: timeout,
);

/// 配对 — 确认方：校验配对码并完成配对（upsert 发起方 + 回复握手 + 自动推送全量快照）。
Future<PairingResult> confirmPairing({
  required SyncService svc,
  required NoteStore store,
  required String code,
  required PairingRequest requester,
}) => RustLib.instance.api.crateApiConfirmPairing(
  svc: svc,
  store: store,
  code: code,
  requester: requester,
);

/// 配对 — 发起方：连接确认方发送配对请求，接收握手响应并 upsert 确认方。
Future<PairingResult> beginPairingConnect({
  required SyncService svc,
  required NoteStore store,
  required String code,
  required PairingTarget target,
}) => RustLib.instance.api.crateApiBeginPairingConnect(
  svc: svc,
  store: store,
  code: code,
  target: target,
);

/// 接受对端推送并导入（首次全量同步接收端；配对成功后发起方调用）。
Future<void> acceptPushAndImport({required SyncService svc}) =>
    RustLib.instance.api.crateApiAcceptPushAndImport(svc: svc);

/// 将所有 CRDT 笔记同步到 SQLite 存储
///
/// 同时清理墓碑（Loro 中已彻底删除的笔记）对应的投影行，防止被删笔记复活。
Future<void> syncNotesToStore({
  required SyncService svc,
  required NoteStore store,
}) => RustLib.instance.api.crateApiSyncNotesToStore(svc: svc, store: store);

/// 设置同步开关（决策 6 能力）：false 时调度器暂停推送与拉取。
/// 移动端由 Flutter 侧按网络类型（WiFi vs 蜂窝）调用；桌面端恒 true。
Future<void> setSyncAllowed({
  required SyncService svc,
  required bool allowed,
}) => RustLib.instance.api.crateApiSetSyncAllowed(svc: svc, allowed: allowed);

/// 当前同步开关状态。
Future<bool> getSyncAllowed({required SyncService svc}) =>
    RustLib.instance.api.crateApiGetSyncAllowed(svc: svc);

/// 待同步笔记计数（模块 5 基础）。
Future<int> pendingSyncCount({required SyncService svc}) =>
    RustLib.instance.api.crateApiPendingSyncCount(svc: svc);

/// 周期拉取间隔（秒）——Flutter 侧 Timer 周期用。
Future<int> syncPollIntervalSecs() =>
    RustLib.instance.api.crateApiSyncPollIntervalSecs();

/// 推送待办（编辑保存即推送）：向所有配对设备推全量快照。
///
/// 失败静默（决策 18）：返回每台设备结果，不抛错；调用方 fire-and-forget 即可。
Future<List<DevicePushResult>> pushPending({
  required SyncService svc,
  required NoteStore store,
}) => RustLib.instance.api.crateApiPushPending(svc: svc, store: store);

/// 周期同步任务体：push 给所有对端 + 短窗口 accept 对端 push + 刷新 SQLite 投影。
Future<SyncCycleResult> runSyncCycle({
  required SyncService svc,
  required NoteStore store,
}) => RustLib.instance.api.crateApiRunSyncCycle(svc: svc, store: store);

/// 创建笔记
Future<void> noteCreate({
  required SyncService svc,
  required String id,
  required String content,
}) =>
    RustLib.instance.api.crateApiNoteCreate(svc: svc, id: id, content: content);

/// 读取笔记内容
Future<String?> noteGet({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNoteGet(svc: svc, id: id);

/// 导出所有笔记的序列化快照
Future<Uint8List> noteExportAll({required SyncService svc}) =>
    RustLib.instance.api.crateApiNoteExportAll(svc: svc);

/// 导入快照
Future<void> noteImportAll({
  required SyncService svc,
  required List<int> data,
}) => RustLib.instance.api.crateApiNoteImportAll(svc: svc, data: data);

/// 推送到对端
Future<void> pushToPeer({
  required SyncService svc,
  required String peerId,
  required List<String> ips,
}) =>
    RustLib.instance.api.crateApiPushToPeer(svc: svc, peerId: peerId, ips: ips);

/// 接受对端推送
Future<Uint8List> acceptPush({required SyncService svc}) =>
    RustLib.instance.api.crateApiAcceptPush(svc: svc);

/// 向多台设备逐个推送全量快照（含墓碑），返回每台设备的结果。
///
/// `devices`: `(peer_id, Option<IP 列表>)`；IP 缺省（None/空）时经 relay/地址解析尝试连接。
/// 单台失败不中断整体；单台超时 10 秒记为失败。
Future<List<DevicePushResult>> pushToDevices({
  required SyncService svc,
  required List<(String, List<String>?)> devices,
}) => RustLib.instance.api.crateApiPushToDevices(svc: svc, devices: devices);

/// SQLite — 列出所有配对设备（最近连接优先）。
Future<List<PairedDeviceRow>> listPairedDevices({required NoteStore store}) =>
    RustLib.instance.api.crateApiListPairedDevices(store: store);

/// SQLite — 移除一台配对设备。
Future<void> removePairedDevice({
  required NoteStore store,
  required String peerId,
}) => RustLib.instance.api.crateApiRemovePairedDevice(
  store: store,
  peerId: peerId,
);

/// 设备发现 — 广播本设备
Future<void> startAdvertising({
  required DiscoveryService disc,
  required String deviceId,
  required int port,
}) => RustLib.instance.api.crateApiStartAdvertising(
  disc: disc,
  deviceId: deviceId,
  port: port,
);

/// 设备发现 — 扫描对端
Future<List<PeerInfo>> discoverPeers({required DiscoveryService disc}) =>
    RustLib.instance.api.crateApiDiscoverPeers(disc: disc);

/// 创建 SQLite 存储
Future<NoteStore> createNoteStore({required String path}) =>
    RustLib.instance.api.crateApiCreateNoteStore(path: path);

/// SQLite — 列出所有笔记
Future<List<NoteRow>> storeList({required NoteStore store}) =>
    RustLib.instance.api.crateApiStoreList(store: store);

/// SQLite — 搜索笔记
Future<List<NoteRow>> storeSearch({
  required NoteStore store,
  required String query,
}) => RustLib.instance.api.crateApiStoreSearch(store: store, query: query);

/// 生成新笔记 ID（UUID v7）
Future<String> generateNoteId() =>
    RustLib.instance.api.crateApiGenerateNoteId();

/// 更新笔记元数据（meta tags）
Future<void> noteUpdateMetadata({
  required SyncService svc,
  required String noteId,
  required List<String> tags,
}) => RustLib.instance.api.crateApiNoteUpdateMetadata(
  svc: svc,
  noteId: noteId,
  tags: tags,
);

/// SQLite — 出链查询
Future<List<LinkRow>> getOutgoingLinks({
  required NoteStore store,
  required String noteId,
}) =>
    RustLib.instance.api.crateApiGetOutgoingLinks(store: store, noteId: noteId);

/// SQLite — 反链查询
Future<List<LinkRow>> getBacklinks({
  required NoteStore store,
  required String noteId,
}) => RustLib.instance.api.crateApiGetBacklinks(store: store, noteId: noteId);

/// SQLite — 全文搜索（FTS5）
Future<List<NoteRow>> searchNotes({
  required NoteStore store,
  required String query,
}) => RustLib.instance.api.crateApiSearchNotes(store: store, query: query);

/// SQLite — 链接自动补全（标题前缀，最近 20 条）
Future<List<NoteRow>> autoCompleteLinks({
  required NoteStore store,
  required String prefix,
}) => RustLib.instance.api.crateApiAutoCompleteLinks(
  store: store,
  prefix: prefix,
);

/// SQLite — 全部标签（去重排序）
Future<List<String>> getAllTags({required NoteStore store}) =>
    RustLib.instance.api.crateApiGetAllTags(store: store);

/// SQLite — 按标签搜索
Future<List<NoteRow>> searchByTag({
  required NoteStore store,
  required String tag,
}) => RustLib.instance.api.crateApiSearchByTag(store: store, tag: tag);

/// SQLite — 回收站列表（deleted_at 非空，按删除时间倒序）
Future<List<NoteRow>> storeTrashList({required NoteStore store}) =>
    RustLib.instance.api.crateApiStoreTrashList(store: store);

/// 软删除：给笔记 meta 打 deleted_at 标记（进回收站）。
/// 删除状态来自 Loro；调用后需由 repository 跟随 `sync_notes_to_store` 刷新投影。
Future<void> noteSoftDelete({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNoteSoftDelete(svc: svc, id: id);

/// 恢复：清除笔记 meta 的 deleted_at 标记。
Future<void> noteRestore({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNoteRestore(svc: svc, id: id);

/// 彻底删除：从 Loro notes 移除并入墓碑（删除信息随快照传播，防复活）。
Future<void> notePurge({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNotePurge(svc: svc, id: id);

/// 过期清理：purge 回收站中 meta.deleted_at < cutoff 的笔记，返回清理数。
///
/// `cutoff` 为 RFC3339 时间字符串（Flutter 侧 `now - 30d`）。
Future<BigInt> purgeExpiredTrash({
  required SyncService svc,
  required String cutoff,
}) => RustLib.instance.api.crateApiPurgeExpiredTrash(svc: svc, cutoff: cutoff);
