// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'discovery.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store.dart';
import 'sync.dart';

/// 创建同步服务
Future<SyncService> createSyncService() =>
    RustLib.instance.api.crateApiCreateSyncService();

/// 创建绑定数据目录的持久化同步服务。
Future<SyncService> createPersistentSyncService({required String path}) =>
    RustLib.instance.api.crateApiCreatePersistentSyncService(path: path);

/// 将所有 CRDT 笔记同步到 SQLite 存储
///
/// 同时清理墓碑（Loro 中已彻底删除的笔记）对应的投影行，防止被删笔记复活。
Future<void> syncNotesToStore({
  required SyncService svc,
  required NoteStore store,
}) => RustLib.instance.api.crateApiSyncNotesToStore(svc: svc, store: store);

/// 创建笔记
Future<void> noteCreate({
  required SyncService svc,
  required String id,
  required String content,
}) =>
    RustLib.instance.api.crateApiNoteCreate(svc: svc, id: id, content: content);

/// 读取笔记内容
Future<String?> noteGet({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNoteGet(svc: svc, id: id);

/// 导出所有笔记的序列化快照
Future<Uint8List> noteExportAll({required SyncService svc}) =>
    RustLib.instance.api.crateApiNoteExportAll(svc: svc);

/// 导入快照
Future<void> noteImportAll({
  required SyncService svc,
  required List<int> data,
}) => RustLib.instance.api.crateApiNoteImportAll(svc: svc, data: data);

/// 推送到对端
Future<void> pushToPeer({
  required SyncService svc,
  required String peerId,
  required List<String> ips,
}) =>
    RustLib.instance.api.crateApiPushToPeer(svc: svc, peerId: peerId, ips: ips);

/// 接受对端推送
Future<Uint8List> acceptPush({required SyncService svc}) =>
    RustLib.instance.api.crateApiAcceptPush(svc: svc);

/// 设备发现 — 广播本设备
Future<void> startAdvertising({
  required DiscoveryService disc,
  required String deviceId,
  required int port,
}) => RustLib.instance.api.crateApiStartAdvertising(
  disc: disc,
  deviceId: deviceId,
  port: port,
);

/// 设备发现 — 扫描对端
Future<List<PeerInfo>> discoverPeers({required DiscoveryService disc}) =>
    RustLib.instance.api.crateApiDiscoverPeers(disc: disc);

/// 创建 SQLite 存储
Future<NoteStore> createNoteStore({required String path}) =>
    RustLib.instance.api.crateApiCreateNoteStore(path: path);

/// SQLite — 列出所有笔记
Future<List<NoteRow>> storeList({required NoteStore store}) =>
    RustLib.instance.api.crateApiStoreList(store: store);

/// SQLite — 搜索笔记
Future<List<NoteRow>> storeSearch({
  required NoteStore store,
  required String query,
}) => RustLib.instance.api.crateApiStoreSearch(store: store, query: query);

/// 生成新笔记 ID（UUID v7）
Future<String> generateNoteId() =>
    RustLib.instance.api.crateApiGenerateNoteId();

/// 更新笔记元数据（meta tags）
Future<void> noteUpdateMetadata({
  required SyncService svc,
  required String noteId,
  required List<String> tags,
}) => RustLib.instance.api.crateApiNoteUpdateMetadata(
  svc: svc,
  noteId: noteId,
  tags: tags,
);

/// SQLite — 出链查询
Future<List<LinkRow>> getOutgoingLinks({
  required NoteStore store,
  required String noteId,
}) =>
    RustLib.instance.api.crateApiGetOutgoingLinks(store: store, noteId: noteId);

/// SQLite — 反链查询
Future<List<LinkRow>> getBacklinks({
  required NoteStore store,
  required String noteId,
}) => RustLib.instance.api.crateApiGetBacklinks(store: store, noteId: noteId);

/// SQLite — 全文搜索（FTS5）
Future<List<NoteRow>> searchNotes({
  required NoteStore store,
  required String query,
}) => RustLib.instance.api.crateApiSearchNotes(store: store, query: query);

/// SQLite — 链接自动补全（标题前缀，最近 20 条）
Future<List<NoteRow>> autoCompleteLinks({
  required NoteStore store,
  required String prefix,
}) => RustLib.instance.api.crateApiAutoCompleteLinks(
  store: store,
  prefix: prefix,
);

/// SQLite — 全部标签（去重排序）
Future<List<String>> getAllTags({required NoteStore store}) =>
    RustLib.instance.api.crateApiGetAllTags(store: store);

/// SQLite — 按标签搜索
Future<List<NoteRow>> searchByTag({
  required NoteStore store,
  required String tag,
}) => RustLib.instance.api.crateApiSearchByTag(store: store, tag: tag);

/// SQLite — 回收站列表（deleted_at 非空，按删除时间倒序）
Future<List<NoteRow>> storeTrashList({required NoteStore store}) =>
    RustLib.instance.api.crateApiStoreTrashList(store: store);

/// 软删除：给笔记 meta 打 deleted_at 标记（进回收站）。
/// 删除状态来自 Loro；调用后需由 repository 跟随 `sync_notes_to_store` 刷新投影。
Future<void> noteSoftDelete({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNoteSoftDelete(svc: svc, id: id);

/// 恢复：清除笔记 meta 的 deleted_at 标记。
Future<void> noteRestore({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNoteRestore(svc: svc, id: id);

/// 彻底删除：从 Loro notes 移除并入墓碑（删除信息随快照传播，防复活）。
Future<void> notePurge({required SyncService svc, required String id}) =>
    RustLib.instance.api.crateApiNotePurge(svc: svc, id: id);

/// 过期清理：purge 回收站中 meta.deleted_at < cutoff 的笔记，返回清理数。
///
/// `cutoff` 为 RFC3339 时间字符串（Flutter 侧 `now - 30d`）。
Future<BigInt> purgeExpiredTrash({
  required SyncService svc,
  required String cutoff,
}) => RustLib.instance.api.crateApiPurgeExpiredTrash(svc: svc, cutoff: cutoff);
