// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteStore>>
abstract class NoteStore implements RustOpaqueInterface {}

/// 链接行（outgoing/backlink 查询结果，FRB 可序列化）
class LinkRow {
  /// 对端笔记 id
  final String id;

  /// 对端实时标题（JOIN 得出，空串 = 悬空）
  final String title;

  /// 源正文里写的显示名
  final String alias;

  /// 对端笔记是否存在（false = 悬空链接）
  final bool exists;

  const LinkRow({
    required this.id,
    required this.title,
    required this.alias,
    required this.exists,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ alias.hashCode ^ exists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          alias == other.alias &&
          exists == other.exists;
}

/// 笔记的只读行（从 SQLite 反查）
class NoteRow {
  final String id;
  final String title;
  final String contentPreview;
  final String tags;
  final String updatedAt;

  /// 软删时间（回收站条目展示"删除于"用；未删除 = None）
  final String? deletedAt;

  const NoteRow({
    required this.id,
    required this.title,
    required this.contentPreview,
    required this.tags,
    required this.updatedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      contentPreview.hashCode ^
      tags.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          contentPreview == other.contentPreview &&
          tags == other.tags &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}

/// 配对设备行（paired_devices 表，FRB 可序列化）
class PairedDeviceRow {
  /// 对端 iroh node id
  final String peerId;

  /// 对端设备名
  final String name;

  /// 最后成功连接/同步时间（ISO8601；尚未连接过 = None）
  final String? lastSeen;

  /// 配对时间（ISO8601）
  final String pairedAt;

  const PairedDeviceRow({
    required this.peerId,
    required this.name,
    this.lastSeen,
    required this.pairedAt,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^ name.hashCode ^ lastSeen.hashCode ^ pairedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairedDeviceRow &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          name == other.name &&
          lastSeen == other.lastSeen &&
          pairedAt == other.pairedAt;
}
