// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteStore>>
abstract class NoteStore implements RustOpaqueInterface {}

/// 链接行（outgoing/backlink 查询结果，FRB 可序列化）
class LinkRow {
  /// 对端笔记 id
  final String id;

  /// 对端实时标题（JOIN 得出，空串 = 悬空）
  final String title;

  /// 源正文里写的显示名
  final String alias;

  /// 对端笔记是否存在（false = 悬空链接）
  final bool exists;

  const LinkRow({
    required this.id,
    required this.title,
    required this.alias,
    required this.exists,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ alias.hashCode ^ exists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          alias == other.alias &&
          exists == other.exists;
}

/// 笔记的只读行（从 SQLite 反查）
class NoteRow {
  final String id;
  final String title;
  final String contentPreview;
  final String tags;
  final String updatedAt;

  const NoteRow({
    required this.id,
    required this.title,
    required this.contentPreview,
    required this.tags,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      contentPreview.hashCode ^
      tags.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          contentPreview == other.contentPreview &&
          tags == other.tags &&
          updatedAt == other.updatedAt;
}
