// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ir.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_card_to_network_impl`, `create_card_impl`, `create_device_impl`, `create_network_impl`, `delete_card_impl`, `delete_network_impl`, `get_cards_impl`, `get_devices_impl`, `get_networks_impl`, `join_network_impl`, `leave_network_impl`, `remove_card_from_network_impl`, `set_resident_network_impl`, `unset_resident_network_impl`, `update_card_impl`, `update_network_impl`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiService>>
abstract class ApiService implements RustOpaqueInterface {
  Future<void> addCardToNetwork({required AddCardToNetworkRequest request});

  Future<Card> createCard({required CreateCardRequest request});

  Future<Device> createDevice({required CreateDeviceRequest request});

  Future<Network> createNetwork({required CreateNetworkRequest request});

  Future<void> deleteCard({required String id});

  Future<void> deleteNetwork({required String id});

  Future<List<Card>> getCards();

  Future<List<Device>> getDevices();

  Future<List<Network>> getNetworks();

  Future<void> joinNetwork({required JoinNetworkRequest request});

  Future<void> leaveNetwork({required LeaveNetworkRequest request});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ApiService> newInstance({required String dbPath}) =>
      RustLib.instance.api.crateApiImplApiServiceNew(dbPath: dbPath);

  Future<void> removeCardFromNetwork({
    required RemoveCardFromNetworkRequest request,
  });

  Future<void> setResidentNetwork({required SetResidentNetworkRequest request});

  Future<void> unsetResidentNetwork({required String deviceId});

  Future<Card> updateCard({required UpdateCardRequest request});

  Future<Network> updateNetwork({required UpdateNetworkRequest request});
}
