// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

class DeviceConfig {
  const DeviceConfig({this.peerId, required this.deviceName, this.poolId, required this.updatedAt});
  final String? peerId;
  final String deviceName;
  final String? poolId;
  final PlatformInt64 updatedAt;

  @override
  int get hashCode => peerId.hashCode ^ deviceName.hashCode ^ poolId.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceConfig &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          deviceName == other.deviceName &&
          poolId == other.poolId &&
          updatedAt == other.updatedAt;
}
