// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

class DeviceConfig {
  const DeviceConfig({required this.deviceId, this.poolId});
  final String deviceId;
  final String? poolId;

  @override
  int get hashCode => deviceId.hashCode ^ poolId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceConfig &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          poolId == other.poolId;
}
