// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../models/card.dart';

// These functions are ignored because they are not marked as `pub`: `get_card_store_arc`, `get_store`

/// Initialize the CardStore with the given storage path
///
/// Must be called before any other API functions.
///
/// # Arguments
///
/// * `path` - Storage root directory path
///
/// # Example (Dart)
///
/// ```dart
/// await initCardStore(path: '/path/to/storage');
/// ```
Future<void> initCardStore({required String path}) =>
    RustLib.instance.api.crateApiCardInitCardStore(path: path);

/// Create a new card
///
/// # Arguments
///
/// * `title` - Card title
/// * `content` - Card content (Markdown format)
///
/// # Returns
///
/// The created Card
///
/// # Notes
///
/// If resident pools are configured, the card will be automatically bound to them.
///
/// # Example (Dart)
///
/// ```dart
/// final card = await createCard(title: 'My Note', content: '# Hello');
/// ```
Future<Card> createCard({required String title, required String content}) =>
    RustLib.instance.api.crateApiCardCreateCard(title: title, content: content);

/// Get all cards (including deleted ones)
///
/// # Returns
///
/// List of all cards, ordered by creation time (newest first)
///
/// # Example (Dart)
///
/// ```dart
/// final cards = await getAllCards();
/// ```
Future<List<Card>> getAllCards() =>
    RustLib.instance.api.crateApiCardGetAllCards();

/// Get all active cards (excluding deleted ones)
///
/// # Returns
///
/// List of active cards, ordered by creation time (newest first)
///
/// # Example (Dart)
///
/// ```dart
/// final cards = await getActiveCards();
/// ```
Future<List<Card>> getActiveCards() =>
    RustLib.instance.api.crateApiCardGetActiveCards();

/// Get a card by ID
///
/// # Arguments
///
/// * `id` - Card ID
///
/// # Returns
///
/// The card if found
///
/// # Errors
///
/// Returns `CardNotFound` error if the card doesn't exist
///
/// # Example (Dart)
///
/// ```dart
/// final card = await getCardById(id: cardId);
/// ```
Future<Card> getCardById({required String id}) =>
    RustLib.instance.api.crateApiCardGetCardById(id: id);

/// Update a card
///
/// # Arguments
///
/// * `id` - Card ID
/// * `title` - New title (optional)
/// * `content` - New content (optional)
///
/// # Example (Dart)
///
/// ```dart
/// await updateCard(id: cardId, title: 'New Title', content: null);
/// ```
Future<void> updateCard({required String id, String? title, String? content}) =>
    RustLib.instance.api.crateApiCardUpdateCard(
      id: id,
      title: title,
      content: content,
    );

/// Delete a card (soft delete)
///
/// # Arguments
///
/// * `id` - Card ID
///
/// # Example (Dart)
///
/// ```dart
/// await deleteCard(id: cardId);
/// ```
Future<void> deleteCard({required String id}) =>
    RustLib.instance.api.crateApiCardDeleteCard(id: id);

/// Get card count statistics
///
/// # Returns
///
/// Tuple of (total_count, active_count, deleted_count)
///
/// # Example (Dart)
///
/// ```dart
/// final (total, active, deleted) = await getCardCount();
/// ```
Future<(PlatformInt64, PlatformInt64, PlatformInt64)> getCardCount() =>
    RustLib.instance.api.crateApiCardGetCardCount();

/// Add card to a data pool
///
/// # Arguments
///
/// * `card_id` - Card ID
/// * `pool_id` - Pool ID
///
/// # Example (Dart)
///
/// ```dart
/// await addCardToPool(cardId: cardId, poolId: poolId);
/// ```
Future<void> addCardToPool({required String cardId, required String poolId}) =>
    RustLib.instance.api.crateApiCardAddCardToPool(
      cardId: cardId,
      poolId: poolId,
    );

/// Remove card from a data pool
///
/// # Arguments
///
/// * `card_id` - Card ID
/// * `pool_id` - Pool ID
///
/// # Example (Dart)
///
/// ```dart
/// await removeCardFromPool(cardId: cardId, poolId: poolId);
/// ```
Future<void> removeCardFromPool({
  required String cardId,
  required String poolId,
}) => RustLib.instance.api.crateApiCardRemoveCardFromPool(
  cardId: cardId,
  poolId: poolId,
);

/// Get all pool IDs that a card belongs to
///
/// # Arguments
///
/// * `card_id` - Card ID
///
/// # Returns
///
/// List of pool IDs
///
/// # Example (Dart)
///
/// ```dart
/// final pools = await getCardPools(cardId: cardId);
/// ```
Future<List<String>> getCardPools({required String cardId}) =>
    RustLib.instance.api.crateApiCardGetCardPools(cardId: cardId);

/// Get all cards in specified pools
///
/// # Arguments
///
/// * `pool_ids` - List of pool IDs
///
/// # Returns
///
/// List of cards (excluding deleted cards)
///
/// # Example (Dart)
///
/// ```dart
/// final cards = await getCardsInPools(poolIds: ['pool1', 'pool2']);
/// ```
Future<List<Card>> getCardsInPools({required List<String> poolIds}) =>
    RustLib.instance.api.crateApiCardGetCardsInPools(poolIds: poolIds);

/// Clear all pool bindings for a card
///
/// # Arguments
///
/// * `card_id` - Card ID
///
/// # Example (Dart)
///
/// ```dart
/// await clearCardPools(cardId: cardId);
/// ```
Future<void> clearCardPools({required String cardId}) =>
    RustLib.instance.api.crateApiCardClearCardPools(cardId: cardId);

/// Test function to verify Flutter-Rust bridge is working
///
/// Returns a greeting message.
String helloCardmind() => RustLib.instance.api.crateApiCardHelloCardmind();

/// Add two numbers (simple test)
int addNumbers({required int a, required int b}) =>
    RustLib.instance.api.crateApiCardAddNumbers(a: a, b: b);
