// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../models/device_config.dart';

// These functions are ignored because they are not marked as `pub`: `save_config`, `with_device_config`

/// Initialize or load device configuration
///
/// If a config file exists at the path, it will be loaded.
/// Otherwise, a new config will be created with a generated device ID.
///
/// # Arguments
///
/// * `base_path` - Storage root directory path
///
/// # Example (Dart)
///
/// ```dart
/// await initDeviceConfig(basePath: '/path/to/storage');
/// ```
Future<DeviceConfig> initDeviceConfig({required String basePath}) =>
    RustLib.instance.api.crateApiDeviceConfigInitDeviceConfig(basePath: basePath);

/// Get the current device configuration
///
/// # Returns
///
/// The current device configuration
///
/// # Example (Dart)
///
/// ```dart
/// final config = await getDeviceConfig();
/// print('Device ID: ${config.deviceId}');
/// ```
Future<DeviceConfig> getDeviceConfig() => RustLib.instance.api.crateApiDeviceConfigGetDeviceConfig();

/// Get the current device ID
///
/// # Returns
///
/// The device UUID
///
/// # Example (Dart)
///
/// ```dart
/// final deviceId = await getDeviceId();
/// ```
Future<String> getDeviceId() => RustLib.instance.api.crateApiDeviceConfigGetDeviceId();

/// Join a data pool
///
/// Adds the pool ID to the joined_pools list.
///
/// # Arguments
///
/// * `pool_id` - Pool ID to join
///
/// # Example (Dart)
///
/// ```dart
/// await joinPool(poolId: poolId);
/// ```
Future<void> joinPool({required String poolId}) => RustLib.instance.api.crateApiDeviceConfigJoinPool(poolId: poolId);

/// Leave a data pool
///
/// Removes the pool ID from joined_pools and resident_pools.
///
/// # Arguments
///
/// * `pool_id` - Pool ID to leave
///
/// # Returns
///
/// true if the pool was found and removed, false otherwise
///
/// # Example (Dart)
///
/// ```dart
/// final left = await leavePool(poolId: poolId);
/// ```
Future<void> leavePool({required String poolId}) => RustLib.instance.api.crateApiDeviceConfigLeavePool(poolId: poolId);

/// Set or unset a pool as resident
///
/// Resident pools are pools that new cards automatically bind to.
///
/// # Arguments
///
/// * `pool_id` - Pool ID
/// * `is_resident` - true to set as resident, false to unset
///
/// # Example (Dart)
///
/// ```dart
/// await setResidentPool(poolId: poolId, isResident: true);
/// ```
Future<void> setResidentPool({required String poolId, required bool isResident}) =>
    RustLib.instance.api.crateApiDeviceConfigSetResidentPool(poolId: poolId, isResident: isResident);

/// Get list of joined pool IDs
///
/// # Returns
///
/// List of pool IDs the device has joined
///
/// # Example (Dart)
///
/// ```dart
/// final joinedPools = await getJoinedPools();
/// ```
Future<List<String>> getJoinedPools() => RustLib.instance.api.crateApiDeviceConfigGetJoinedPools();

/// Get list of resident pool IDs
///
/// # Returns
///
/// List of pool IDs marked as resident
///
/// # Example (Dart)
///
/// ```dart
/// final residentPools = await getResidentPools();
/// ```
Future<List<String>> getResidentPools() => RustLib.instance.api.crateApiDeviceConfigGetResidentPools();

/// Check if the device has joined a pool
///
/// # Arguments
///
/// * `pool_id` - Pool ID to check
///
/// # Returns
///
/// true if joined, false otherwise
///
/// # Example (Dart)
///
/// ```dart
/// final hasJoined = await isPoolJoined(poolId: poolId);
/// ```
Future<bool> isPoolJoined({required String poolId}) =>
    RustLib.instance.api.crateApiDeviceConfigIsPoolJoined(poolId: poolId);

/// Check if a pool is marked as resident
///
/// # Arguments
///
/// * `pool_id` - Pool ID to check
///
/// # Returns
///
/// true if resident, false otherwise
///
/// # Example (Dart)
///
/// ```dart
/// final isResident = await isPoolResident(poolId: poolId);
/// ```
Future<bool> isPoolResident({required String poolId}) =>
    RustLib.instance.api.crateApiDeviceConfigIsPoolResident(poolId: poolId);

/// Check if mDNS peer discovery is currently active
///
/// mDNS is active only within the 5-minute timer window after being enabled.
///
/// # Returns
///
/// true if mDNS is active, false otherwise
///
/// # Example (Dart)
///
/// ```dart
/// final isActive = await isMdnsActive();
/// ```
Future<bool> isMdnsActive() => RustLib.instance.api.crateApiDeviceConfigIsMdnsActive();

/// Enable mDNS peer discovery for 5 minutes
///
/// Starts a 5-minute timer for mDNS discovery. After 5 minutes,
/// mDNS will automatically be disabled. Timer does not persist
/// across app restarts (security feature).
///
/// # Example (Dart)
///
/// ```dart
/// await enableMdnsTemporary();
/// ```
Future<void> enableMdnsTemporary() => RustLib.instance.api.crateApiDeviceConfigEnableMdnsTemporary();

/// Cancel the mDNS timer immediately
///
/// Disables mDNS discovery right away.
///
/// # Example (Dart)
///
/// ```dart
/// await cancelMdnsTimer();
/// ```
Future<void> cancelMdnsTimer() => RustLib.instance.api.crateApiDeviceConfigCancelMdnsTimer();

/// Get remaining time for mDNS discovery (in milliseconds)
///
/// Returns 0 if mDNS is not active or has expired.
///
/// # Returns
///
/// Remaining time in milliseconds
///
/// # Example (Dart)
///
/// ```dart
/// final remainingMs = await getMdnsRemainingMs();
/// ```
Future<PlatformInt64> getMdnsRemainingMs() => RustLib.instance.api.crateApiDeviceConfigGetMdnsRemainingMs();
