// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ir.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1923073235;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cardmind_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiIrApiServiceAddCardToNetwork({
    required ApiService that,
    required AddCardToNetworkRequest request,
  });

  Card crateApiIrApiServiceCreateCard({
    required ApiService that,
    required CreateCardRequest request,
  });

  Device crateApiIrApiServiceCreateDevice({
    required ApiService that,
    required CreateDeviceRequest request,
  });

  Network crateApiIrApiServiceCreateNetwork({
    required ApiService that,
    required CreateNetworkRequest request,
  });

  void crateApiIrApiServiceDeleteCard({
    required ApiService that,
    required String id,
  });

  void crateApiIrApiServiceDeleteNetwork({
    required ApiService that,
    required String id,
  });

  List<Card> crateApiIrApiServiceGetCards({required ApiService that});

  List<Device> crateApiIrApiServiceGetDevices({required ApiService that});

  List<Network> crateApiIrApiServiceGetNetworks({required ApiService that});

  void crateApiIrApiServiceJoinNetwork({
    required ApiService that,
    required JoinNetworkRequest request,
  });

  void crateApiIrApiServiceLeaveNetwork({
    required ApiService that,
    required LeaveNetworkRequest request,
  });

  ApiService crateApiIrApiServiceNew({required String dbPath});

  void crateApiIrApiServiceRemoveCardFromNetwork({
    required ApiService that,
    required RemoveCardFromNetworkRequest request,
  });

  void crateApiIrApiServiceSetResidentNetwork({
    required ApiService that,
    required SetResidentNetworkRequest request,
  });

  void crateApiIrApiServiceUnsetResidentNetwork({
    required ApiService that,
    required String deviceId,
  });

  Card crateApiIrApiServiceUpdateCard({
    required ApiService that,
    required UpdateCardRequest request,
  });

  Network crateApiIrApiServiceUpdateNetwork({
    required ApiService that,
    required UpdateNetworkRequest request,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AddCardToNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AddCardToNetworkRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AddCardToNetworkRequestPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiService;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ApiServicePtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Card;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Card;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CardPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CreateCardRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CreateCardRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CreateCardRequestPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CreateDeviceRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CreateDeviceRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CreateDeviceRequestPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CreateNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CreateNetworkRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CreateNetworkRequestPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Device;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Device;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DevicePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JoinNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JoinNetworkRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_JoinNetworkRequestPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LeaveNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LeaveNetworkRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LeaveNetworkRequestPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Network;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Network;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_NetworkPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RemoveCardFromNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RemoveCardFromNetworkRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RemoveCardFromNetworkRequestPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SetResidentNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SetResidentNetworkRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SetResidentNetworkRequestPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UpdateCardRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UpdateCardRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UpdateCardRequestPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UpdateNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UpdateNetworkRequest;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UpdateNetworkRequestPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiIrApiServiceAddCardToNetwork({
    required ApiService that,
    required AddCardToNetworkRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceAddCardToNetworkConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceAddCardToNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_add_card_to_network",
        argNames: ["that", "request"],
      );

  @override
  Card crateApiIrApiServiceCreateCard({
    required ApiService that,
    required CreateCardRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceCreateCardConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceCreateCardConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_create_card",
        argNames: ["that", "request"],
      );

  @override
  Device crateApiIrApiServiceCreateDevice({
    required ApiService that,
    required CreateDeviceRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceCreateDeviceConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceCreateDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_create_device",
        argNames: ["that", "request"],
      );

  @override
  Network crateApiIrApiServiceCreateNetwork({
    required ApiService that,
    required CreateNetworkRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceCreateNetworkConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceCreateNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_create_network",
        argNames: ["that", "request"],
      );

  @override
  void crateApiIrApiServiceDeleteCard({
    required ApiService that,
    required String id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceDeleteCardConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceDeleteCardConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_delete_card",
        argNames: ["that", "id"],
      );

  @override
  void crateApiIrApiServiceDeleteNetwork({
    required ApiService that,
    required String id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceDeleteNetworkConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceDeleteNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_delete_network",
        argNames: ["that", "id"],
      );

  @override
  List<Card> crateApiIrApiServiceGetCards({required ApiService that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceGetCardsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceGetCardsConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_get_cards",
        argNames: ["that"],
      );

  @override
  List<Device> crateApiIrApiServiceGetDevices({required ApiService that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceGetDevicesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceGetDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_get_devices",
        argNames: ["that"],
      );

  @override
  List<Network> crateApiIrApiServiceGetNetworks({required ApiService that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceGetNetworksConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceGetNetworksConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_get_networks",
        argNames: ["that"],
      );

  @override
  void crateApiIrApiServiceJoinNetwork({
    required ApiService that,
    required JoinNetworkRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceJoinNetworkConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceJoinNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_join_network",
        argNames: ["that", "request"],
      );

  @override
  void crateApiIrApiServiceLeaveNetwork({
    required ApiService that,
    required LeaveNetworkRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceLeaveNetworkConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceLeaveNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_leave_network",
        argNames: ["that", "request"],
      );

  @override
  ApiService crateApiIrApiServiceNew({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceNewConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceNewConstMeta =>
      const TaskConstMeta(debugName: "ApiService_new", argNames: ["dbPath"]);

  @override
  void crateApiIrApiServiceRemoveCardFromNetwork({
    required ApiService that,
    required RemoveCardFromNetworkRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceRemoveCardFromNetworkConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceRemoveCardFromNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_remove_card_from_network",
        argNames: ["that", "request"],
      );

  @override
  void crateApiIrApiServiceSetResidentNetwork({
    required ApiService that,
    required SetResidentNetworkRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceSetResidentNetworkConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceSetResidentNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_set_resident_network",
        argNames: ["that", "request"],
      );

  @override
  void crateApiIrApiServiceUnsetResidentNetwork({
    required ApiService that,
    required String deviceId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_String(deviceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceUnsetResidentNetworkConstMeta,
        argValues: [that, deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceUnsetResidentNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_unset_resident_network",
        argNames: ["that", "deviceId"],
      );

  @override
  Card crateApiIrApiServiceUpdateCard({
    required ApiService that,
    required UpdateCardRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceUpdateCardConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceUpdateCardConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_update_card",
        argNames: ["that", "request"],
      );

  @override
  Network crateApiIrApiServiceUpdateNetwork({
    required ApiService that,
    required UpdateNetworkRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest(
            request,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrApiServiceUpdateNetworkConstMeta,
        argValues: [that, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrApiServiceUpdateNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_update_network",
        argNames: ["that", "request"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AddCardToNetworkRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AddCardToNetworkRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Card => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Card => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CreateCardRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CreateCardRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CreateDeviceRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CreateDeviceRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CreateNetworkRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CreateNetworkRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Device => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Device => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JoinNetworkRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JoinNetworkRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LeaveNetworkRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LeaveNetworkRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Network => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Network => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RemoveCardFromNetworkRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RemoveCardFromNetworkRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SetResidentNetworkRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SetResidentNetworkRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UpdateCardRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UpdateCardRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UpdateNetworkRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UpdateNetworkRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest;

  @protected
  AddCardToNetworkRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AddCardToNetworkRequestImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ApiService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Card
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CardImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CreateCardRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CreateCardRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CreateDeviceRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CreateDeviceRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CreateNetworkRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CreateNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Device
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JoinNetworkRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JoinNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LeaveNetworkRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LeaveNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Network
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RemoveCardFromNetworkRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RemoveCardFromNetworkRequestImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  SetResidentNetworkRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SetResidentNetworkRequestImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  UpdateCardRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UpdateCardRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UpdateNetworkRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UpdateNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AddCardToNetworkRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AddCardToNetworkRequestImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ApiService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Card
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CardImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CreateCardRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CreateCardRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CreateDeviceRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CreateDeviceRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CreateNetworkRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CreateNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Device
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JoinNetworkRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JoinNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LeaveNetworkRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LeaveNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Network
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RemoveCardFromNetworkRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RemoveCardFromNetworkRequestImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  SetResidentNetworkRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SetResidentNetworkRequestImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  UpdateCardRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UpdateCardRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UpdateNetworkRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UpdateNetworkRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  List<Card>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard,
        )
        .toList();
  }

  @protected
  List<Device>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice,
        )
        .toList();
  }

  @protected
  List<Network>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork,
        )
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AddCardToNetworkRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AddCardToNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Card
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CardImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CreateCardRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CreateCardRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CreateDeviceRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CreateDeviceRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CreateNetworkRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CreateNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Device
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DeviceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JoinNetworkRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JoinNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LeaveNetworkRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LeaveNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Network
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RemoveCardFromNetworkRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RemoveCardFromNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SetResidentNetworkRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SetResidentNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UpdateCardRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UpdateCardRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UpdateNetworkRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UpdateNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AddCardToNetworkRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AddCardToNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Card
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CardImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CreateCardRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CreateCardRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CreateDeviceRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CreateDeviceRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CreateNetworkRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CreateNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Device
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DeviceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JoinNetworkRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JoinNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LeaveNetworkRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LeaveNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Network
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RemoveCardFromNetworkRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RemoveCardFromNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SetResidentNetworkRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SetResidentNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UpdateCardRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UpdateCardRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UpdateNetworkRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UpdateNetworkRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  List<Card>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Card>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<Device>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Device>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<Network>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Network>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest(
    AddCardToNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AddCardToNetworkRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    ApiService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    Card self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CardImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest(
    CreateCardRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CreateCardRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest(
    CreateDeviceRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CreateDeviceRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest(
    CreateNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CreateNetworkRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    Device self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DeviceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest(
    JoinNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JoinNetworkRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest(
    LeaveNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LeaveNetworkRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    Network self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest(
    RemoveCardFromNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RemoveCardFromNetworkRequestImpl).frbInternalSseEncode(
        move: true,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest(
    SetResidentNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SetResidentNetworkRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest(
    UpdateCardRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UpdateCardRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest(
    UpdateNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UpdateNetworkRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    ApiService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddCardToNetworkRequest(
    AddCardToNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AddCardToNetworkRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    ApiService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    Card self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CardImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateCardRequest(
    CreateCardRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CreateCardRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateDeviceRequest(
    CreateDeviceRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CreateDeviceRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCreateNetworkRequest(
    CreateNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CreateNetworkRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    Device self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DeviceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinNetworkRequest(
    JoinNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JoinNetworkRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLeaveNetworkRequest(
    LeaveNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LeaveNetworkRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    Network self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoveCardFromNetworkRequest(
    RemoveCardFromNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RemoveCardFromNetworkRequestImpl).frbInternalSseEncode(
        move: null,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSetResidentNetworkRequest(
    SetResidentNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SetResidentNetworkRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateCardRequest(
    UpdateCardRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UpdateCardRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUpdateNetworkRequest(
    UpdateNetworkRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UpdateNetworkRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
    List<Card> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCard(
        item,
        serializer,
      );
    }
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    List<Device> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
        item,
        serializer,
      );
    }
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
    List<Network> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetwork(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AddCardToNetworkRequestImpl extends RustOpaque
    implements AddCardToNetworkRequest {
  // Not to be used by end users
  AddCardToNetworkRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AddCardToNetworkRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_AddCardToNetworkRequest,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_AddCardToNetworkRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_AddCardToNetworkRequestPtr,
  );
}

@sealed
class ApiServiceImpl extends RustOpaque implements ApiService {
  // Not to be used by end users
  ApiServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ApiService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiService,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiServicePtr,
  );

  void addCardToNetwork({required AddCardToNetworkRequest request}) => RustLib
      .instance
      .api
      .crateApiIrApiServiceAddCardToNetwork(that: this, request: request);

  Card createCard({required CreateCardRequest request}) => RustLib.instance.api
      .crateApiIrApiServiceCreateCard(that: this, request: request);

  Device createDevice({required CreateDeviceRequest request}) => RustLib
      .instance
      .api
      .crateApiIrApiServiceCreateDevice(that: this, request: request);

  Network createNetwork({required CreateNetworkRequest request}) => RustLib
      .instance
      .api
      .crateApiIrApiServiceCreateNetwork(that: this, request: request);

  void deleteCard({required String id}) =>
      RustLib.instance.api.crateApiIrApiServiceDeleteCard(that: this, id: id);

  void deleteNetwork({required String id}) => RustLib.instance.api
      .crateApiIrApiServiceDeleteNetwork(that: this, id: id);

  List<Card> getCards() =>
      RustLib.instance.api.crateApiIrApiServiceGetCards(that: this);

  List<Device> getDevices() =>
      RustLib.instance.api.crateApiIrApiServiceGetDevices(that: this);

  List<Network> getNetworks() =>
      RustLib.instance.api.crateApiIrApiServiceGetNetworks(that: this);

  void joinNetwork({required JoinNetworkRequest request}) => RustLib
      .instance
      .api
      .crateApiIrApiServiceJoinNetwork(that: this, request: request);

  void leaveNetwork({required LeaveNetworkRequest request}) => RustLib
      .instance
      .api
      .crateApiIrApiServiceLeaveNetwork(that: this, request: request);

  void removeCardFromNetwork({required RemoveCardFromNetworkRequest request}) =>
      RustLib.instance.api.crateApiIrApiServiceRemoveCardFromNetwork(
        that: this,
        request: request,
      );

  void setResidentNetwork({required SetResidentNetworkRequest request}) =>
      RustLib.instance.api.crateApiIrApiServiceSetResidentNetwork(
        that: this,
        request: request,
      );

  void unsetResidentNetwork({required String deviceId}) => RustLib.instance.api
      .crateApiIrApiServiceUnsetResidentNetwork(that: this, deviceId: deviceId);

  Card updateCard({required UpdateCardRequest request}) => RustLib.instance.api
      .crateApiIrApiServiceUpdateCard(that: this, request: request);

  Network updateNetwork({required UpdateNetworkRequest request}) => RustLib
      .instance
      .api
      .crateApiIrApiServiceUpdateNetwork(that: this, request: request);
}

@sealed
class CardImpl extends RustOpaque implements Card {
  // Not to be used by end users
  CardImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CardImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Card,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Card,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CardPtr,
  );
}

@sealed
class CreateCardRequestImpl extends RustOpaque implements CreateCardRequest {
  // Not to be used by end users
  CreateCardRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CreateCardRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CreateCardRequest,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CreateCardRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CreateCardRequestPtr,
  );
}

@sealed
class CreateDeviceRequestImpl extends RustOpaque
    implements CreateDeviceRequest {
  // Not to be used by end users
  CreateDeviceRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CreateDeviceRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_CreateDeviceRequest,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CreateDeviceRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CreateDeviceRequestPtr,
  );
}

@sealed
class CreateNetworkRequestImpl extends RustOpaque
    implements CreateNetworkRequest {
  // Not to be used by end users
  CreateNetworkRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CreateNetworkRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_CreateNetworkRequest,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CreateNetworkRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CreateNetworkRequestPtr,
  );
}

@sealed
class DeviceImpl extends RustOpaque implements Device {
  // Not to be used by end users
  DeviceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DeviceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Device,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Device,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_DevicePtr,
  );
}

@sealed
class JoinNetworkRequestImpl extends RustOpaque implements JoinNetworkRequest {
  // Not to be used by end users
  JoinNetworkRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  JoinNetworkRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_JoinNetworkRequest,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_JoinNetworkRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_JoinNetworkRequestPtr,
  );
}

@sealed
class LeaveNetworkRequestImpl extends RustOpaque
    implements LeaveNetworkRequest {
  // Not to be used by end users
  LeaveNetworkRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LeaveNetworkRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_LeaveNetworkRequest,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_LeaveNetworkRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_LeaveNetworkRequestPtr,
  );
}

@sealed
class NetworkImpl extends RustOpaque implements Network {
  // Not to be used by end users
  NetworkImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NetworkImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Network,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Network,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NetworkPtr,
  );
}

@sealed
class RemoveCardFromNetworkRequestImpl extends RustOpaque
    implements RemoveCardFromNetworkRequest {
  // Not to be used by end users
  RemoveCardFromNetworkRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RemoveCardFromNetworkRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_RemoveCardFromNetworkRequest,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_RemoveCardFromNetworkRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_RemoveCardFromNetworkRequestPtr,
  );
}

@sealed
class SetResidentNetworkRequestImpl extends RustOpaque
    implements SetResidentNetworkRequest {
  // Not to be used by end users
  SetResidentNetworkRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SetResidentNetworkRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_SetResidentNetworkRequest,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_SetResidentNetworkRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_SetResidentNetworkRequestPtr,
  );
}

@sealed
class UpdateCardRequestImpl extends RustOpaque implements UpdateCardRequest {
  // Not to be used by end users
  UpdateCardRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  UpdateCardRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_UpdateCardRequest,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_UpdateCardRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_UpdateCardRequestPtr,
  );
}

@sealed
class UpdateNetworkRequestImpl extends RustOpaque
    implements UpdateNetworkRequest {
  // Not to be used by end users
  UpdateNetworkRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  UpdateNetworkRequestImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_UpdateNetworkRequest,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_UpdateNetworkRequest,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_UpdateNetworkRequestPtr,
  );
}
