name: cardmind
description: 卡片笔记应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI 组件
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.7.6+2
  google_fonts: ^6.1.0
  # 状态管理
  flutter_riverpod: ^2.4.10
  # 路由管理
  go_router: ^14.8.1
  # 数据存储和同步
  sqlite3_flutter_libs: ^0.5.18
  sqflite: ^2.3.2
  sql_crdt: ^3.0.2
  sqlite_crdt: ^3.0.2
  # 工具库
  path: ^1.8.3
  uuid: ^4.5.1
  path_provider: ^2.1.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
