[package]
name = "cardmind-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "fs"] }
axum = { version = "0.7", features = ["http1", "tokio", "json", "macros"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["cors", "trace"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
chrono = { version = "0.4", features = ["serde", "clock"] }
dotenv = "0.15"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
