// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

/// # API 桥接层
///
/// 提供 Flutter 与 Rust 后端之间的 FFI 桥接 API。
/// 包含卡片、数据池、同步等核心功能的 Dart 侧接口。
library bridge_api;

import 'frb_generated.dart';
import 'models/api_error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'runtime/config.dart';
import 'runtime/entry_manager.dart';

// These functions are ignored because they are not marked as `pub`: `app_config_dir`, `combine_sync_result`, `combine_sync_status`, `configured_app_data_dir`, `list_all_card_ids`, `parse_card_id`, `parse_pool_id`, `pool_network_map`, `projection_state`, `with_configured_card_store`, `with_configured_pool_store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 获取后端配置
Future<BackendConfigDto> getBackendConfig() =>
    RustLib.instance.api.crateApiGetBackendConfig();

/// 更新后端配置
Future<BackendConfigDto> updateBackendConfig({
  required bool httpEnabled,
  required bool mcpEnabled,
  required bool cliEnabled,
}) => RustLib.instance.api.crateApiUpdateBackendConfig(
  httpEnabled: httpEnabled,
  mcpEnabled: mcpEnabled,
  cliEnabled: cliEnabled,
);

/// 获取运行时入口状态
Future<RuntimeEntryStatusDto> getRuntimeEntryStatus() =>
    RustLib.instance.api.crateApiGetRuntimeEntryStatus();

/// 初始化应用级配置
Future<void> initAppConfig({required String appDataDir}) =>
    RustLib.instance.api.crateApiInitAppConfig(appDataDir: appDataDir);

/// 重置应用配置（仅用于测试）
Future<void> resetAppConfigForTests() =>
    RustLib.instance.api.crateApiResetAppConfigForTests();

/// 创建数据池
Future<PoolDto> createPool({
  required String endpointId,
  required String nickname,
  required String os,
}) => RustLib.instance.api.crateApiCreatePool(
  endpointId: endpointId,
  nickname: nickname,
  os: os,
);

/// 加入数据池
Future<PoolDto> joinPool({
  required String poolId,
  required String endpointId,
  required String nickname,
  required String os,
}) => RustLib.instance.api.crateApiJoinPool(
  poolId: poolId,
  endpointId: endpointId,
  nickname: nickname,
  os: os,
);

/// 通过邀请码加入数据池
Future<PoolDto> joinByCode({
  required String code,
  required String endpointId,
  required String nickname,
  required String os,
}) => RustLib.instance.api.crateApiJoinByCode(
  code: code,
  endpointId: endpointId,
  nickname: nickname,
  os: os,
);

/// 列出指定端点加入的所有数据池
Future<List<PoolDto>> listPools({required String endpointId}) =>
    RustLib.instance.api.crateApiListPools(endpointId: endpointId);

/// 获取数据池详情
Future<PoolDetailDto> getPoolDetail({
  required String poolId,
  required String endpointId,
}) => RustLib.instance.api.crateApiGetPoolDetail(
  poolId: poolId,
  endpointId: endpointId,
);

/// 获取已加入数据池的视图
Future<PoolDetailDto> getJoinedPoolView({required String endpointId}) =>
    RustLib.instance.api.crateApiGetJoinedPoolView(endpointId: endpointId);

/// 创建卡片笔记
Future<CardNoteDto> createCardNote({
  required String title,
  required String content,
}) =>
    RustLib.instance.api.crateApiCreateCardNote(title: title, content: content);

/// 在指定数据池中创建卡片笔记
Future<CardNoteDto> createCardNoteInPool({
  required String poolId,
  required String title,
  required String content,
}) => RustLib.instance.api.crateApiCreateCardNoteInPool(
  poolId: poolId,
  title: title,
  content: content,
);

/// 更新卡片笔记
Future<CardNoteDto> updateCardNote({
  required String cardId,
  required String title,
  required String content,
}) => RustLib.instance.api.crateApiUpdateCardNote(
  cardId: cardId,
  title: title,
  content: content,
);

/// 软删除卡片笔记
Future<CardNoteDto> deleteCardNote({required String cardId}) =>
    RustLib.instance.api.crateApiDeleteCardNote(cardId: cardId);

/// 恢复已删除的卡片笔记
Future<CardNoteDto> restoreCardNote({required String cardId}) =>
    RustLib.instance.api.crateApiRestoreCardNote(cardId: cardId);

/// 列出所有卡片笔记
Future<List<CardNoteDto>> listCardNotes() =>
    RustLib.instance.api.crateApiListCardNotes();

/// 搜索卡片笔记
Future<List<CardNoteDto>> queryCardNotes({
  required String query,
  String? poolId,
  bool? includeDeleted,
}) => RustLib.instance.api.crateApiQueryCardNotes(
  query: query,
  poolId: poolId,
  includeDeleted: includeDeleted,
);

/// 获取卡片笔记详情
Future<CardNoteDto> getCardNoteDetail({required String cardId}) =>
    RustLib.instance.api.crateApiGetCardNoteDetail(cardId: cardId);

/// 初始化 PoolNetwork
Future<BigInt> initPoolNetwork({required String basePath}) =>
    RustLib.instance.api.crateApiInitPoolNetwork(basePath: basePath);

/// 关闭 PoolNetwork
Future<void> closePoolNetwork({required BigInt networkId}) =>
    RustLib.instance.api.crateApiClosePoolNetwork(networkId: networkId);

/// 获取同步状态
Future<SyncStatusDto> syncStatus({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncStatus(networkId: networkId);

/// 建立同步连接
Future<void> syncConnect({required BigInt networkId, required String target}) =>
    RustLib.instance.api.crateApiSyncConnect(
      networkId: networkId,
      target: target,
    );

/// 断开同步连接
Future<void> syncDisconnect({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncDisconnect(networkId: networkId);

/// 加入同步池
Future<void> syncJoinPool({
  required BigInt networkId,
  required String poolId,
}) => RustLib.instance.api.crateApiSyncJoinPool(
  networkId: networkId,
  poolId: poolId,
);

/// 推送同步数据
Future<SyncResultDto> syncPush({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncPush(networkId: networkId);

/// 拉取同步数据
Future<SyncResultDto> syncPull({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncPull(networkId: networkId);

/// 卡片笔记数据传输对象
class CardNoteDto {
  /// 卡片 ID
  final String id;

  /// 卡片标题
  final String title;

  /// 卡片内容
  final String content;

  /// 创建时间戳
  final PlatformInt64 createdAt;

  /// 更新时间戳
  final PlatformInt64 updatedAt;

  /// 是否已删除
  final bool deleted;

  /// 创建 CardNoteDto 实例
  const CardNoteDto({
    required this.id,
    required this.title,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
    required this.deleted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardNoteDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          content == other.content &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deleted == other.deleted;
}

/// 数据池详情数据传输对象
class PoolDetailDto {
  /// 数据池 ID
  final String id;

  /// 数据池名称
  final String name;

  /// 是否已解散
  final bool isDissolved;

  /// 当前用户角色
  final String currentUserRole;

  /// 成员数量
  final BigInt memberCount;

  /// 笔记 ID 列表
  final List<String> noteIds;

  /// 成员列表
  final List<PoolMemberDto> members;

  /// 创建 PoolDetailDto 实例
  const PoolDetailDto({
    required this.id,
    required this.name,
    required this.isDissolved,
    required this.currentUserRole,
    required this.memberCount,
    required this.noteIds,
    required this.members,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isDissolved.hashCode ^
      currentUserRole.hashCode ^
      memberCount.hashCode ^
      noteIds.hashCode ^
      members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDissolved == other.isDissolved &&
          currentUserRole == other.currentUserRole &&
          memberCount == other.memberCount &&
          noteIds == other.noteIds &&
          members == other.members;
}

/// 数据池数据传输对象
class PoolDto {
  /// 数据池 ID
  final String id;

  /// 数据池名称
  final String name;

  /// 是否已解散
  final bool isDissolved;

  /// 当前用户角色
  final String currentUserRole;

  /// 成员数量
  final BigInt memberCount;

  /// 创建 PoolDto 实例
  const PoolDto({
    required this.id,
    required this.name,
    required this.isDissolved,
    required this.currentUserRole,
    required this.memberCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isDissolved.hashCode ^
      currentUserRole.hashCode ^
      memberCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDissolved == other.isDissolved &&
          currentUserRole == other.currentUserRole &&
          memberCount == other.memberCount;
}

/// 数据池成员数据传输对象
class PoolMemberDto {
  /// 端点 ID
  final String endpointId;

  /// 昵称
  final String nickname;

  /// 操作系统
  final String os;

  /// 角色
  final String role;

  /// 创建 PoolMemberDto 实例
  const PoolMemberDto({
    required this.endpointId,
    required this.nickname,
    required this.os,
    required this.role,
  });

  @override
  int get hashCode =>
      endpointId.hashCode ^ nickname.hashCode ^ os.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolMemberDto &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          nickname == other.nickname &&
          os == other.os &&
          role == other.role;
}

/// 同步结果数据传输对象
class SyncResultDto {
  /// 同步状态
  final String syncState;

  /// 查询收敛状态
  final String queryConvergenceState;

  /// 实例连续性状态
  final String instanceContinuityState;

  /// 本地内容安全状态
  final String localContentSafety;

  /// 恢复阶段
  final String recoveryStage;

  /// 连续性状态
  final String continuityState;

  /// 下一步动作
  final String nextAction;

  /// 允许的操作列表
  final List<String> allowedOperations;

  /// 禁止的操作列表
  final List<String> forbiddenOperations;

  /// 恢复码
  final String? code;

  /// 状态
  final String state;

  /// 写入状态
  final String writeState;

  /// 投影状态
  final String projectionState;

  /// 内容状态
  final String contentState;

  /// 创建 SyncResultDto 实例
  const SyncResultDto({
    required this.syncState,
    required this.queryConvergenceState,
    required this.instanceContinuityState,
    required this.localContentSafety,
    required this.recoveryStage,
    required this.continuityState,
    required this.nextAction,
    required this.allowedOperations,
    required this.forbiddenOperations,
    this.code,
    required this.state,
    required this.writeState,
    required this.projectionState,
    required this.contentState,
  });

  @override
  int get hashCode =>
      syncState.hashCode ^
      queryConvergenceState.hashCode ^
      instanceContinuityState.hashCode ^
      localContentSafety.hashCode ^
      recoveryStage.hashCode ^
      continuityState.hashCode ^
      nextAction.hashCode ^
      allowedOperations.hashCode ^
      forbiddenOperations.hashCode ^
      code.hashCode ^
      state.hashCode ^
      writeState.hashCode ^
      projectionState.hashCode ^
      contentState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResultDto &&
          runtimeType == other.runtimeType &&
          syncState == other.syncState &&
          queryConvergenceState == other.queryConvergenceState &&
          instanceContinuityState == other.instanceContinuityState &&
          localContentSafety == other.localContentSafety &&
          recoveryStage == other.recoveryStage &&
          continuityState == other.continuityState &&
          nextAction == other.nextAction &&
          allowedOperations == other.allowedOperations &&
          forbiddenOperations == other.forbiddenOperations &&
          code == other.code &&
          state == other.state &&
          writeState == other.writeState &&
          projectionState == other.projectionState &&
          contentState == other.contentState;
}

/// 同步状态数据传输对象
class SyncStatusDto {
  /// 同步状态
  final String syncState;

  /// 查询收敛状态
  final String queryConvergenceState;

  /// 实例连续性状态
  final String instanceContinuityState;

  /// 本地内容安全状态
  final String localContentSafety;

  /// 恢复阶段
  final String recoveryStage;

  /// 连续性状态
  final String continuityState;

  /// 下一步动作
  final String nextAction;

  /// 允许的操作列表
  final List<String> allowedOperations;

  /// 禁止的操作列表
  final List<String> forbiddenOperations;

  /// 恢复码
  final String? code;

  /// 状态
  final String state;

  /// 写入状态
  final String writeState;

  /// 投影状态
  final String projectionState;

  /// 内容状态
  final String contentState;

  /// 创建 SyncStatusDto 实例
  const SyncStatusDto({
    required this.syncState,
    required this.queryConvergenceState,
    required this.instanceContinuityState,
    required this.localContentSafety,
    required this.recoveryStage,
    required this.continuityState,
    required this.nextAction,
    required this.allowedOperations,
    required this.forbiddenOperations,
    this.code,
    required this.state,
    required this.writeState,
    required this.projectionState,
    required this.contentState,
  });

  @override
  int get hashCode =>
      syncState.hashCode ^
      queryConvergenceState.hashCode ^
      instanceContinuityState.hashCode ^
      localContentSafety.hashCode ^
      recoveryStage.hashCode ^
      continuityState.hashCode ^
      nextAction.hashCode ^
      allowedOperations.hashCode ^
      forbiddenOperations.hashCode ^
      code.hashCode ^
      state.hashCode ^
      writeState.hashCode ^
      projectionState.hashCode ^
      contentState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          syncState == other.syncState &&
          queryConvergenceState == other.queryConvergenceState &&
          instanceContinuityState == other.instanceContinuityState &&
          localContentSafety == other.localContentSafety &&
          recoveryStage == other.recoveryStage &&
          continuityState == other.continuityState &&
          nextAction == other.nextAction &&
          allowedOperations == other.allowedOperations &&
          forbiddenOperations == other.forbiddenOperations &&
          code == other.code &&
          state == other.state &&
          writeState == other.writeState &&
          projectionState == other.projectionState &&
          contentState == other.contentState;
}
