// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models/api_error.dart';
import 'models/pool_runtime.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'runtime/config.dart';
import 'runtime/entry_manager.dart';
import 'store/pool_store.dart';

// These functions are ignored because they are not marked as `pub`: `app_config_dir`, `app_lock_state`, `build_pool_runtime_rows`, `build_pool_runtime_summary`, `combine_sync_result`, `combine_sync_status`, `configured_app_data_dir`, `list_all_card_ids`, `network_runtime_signals_for_pool_member`, `parse_card_id`, `parse_invite_id`, `parse_pool_id`, `parse_sync_target`, `pool_network_map`, `projection_state`, `require_app_lock_unlocked`, `to_join_request_dtos`, `with_configured_card_store`, `with_configured_pool_store`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ManagedPoolNetwork`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 获取后端服务配置
///
/// 读取当前启用的后端接口（HTTP/MCP/CLI）配置状态。
///
/// # Returns
/// - `Ok(BackendConfigDto)` - 当前配置，包含 http_enabled、mcp_enabled、cli_enabled 字段
/// - `Err(ApiError)` - 配置读取失败
///
/// # Panics
/// - 应用配置未初始化时返回 `ApiErrorCode::AppConfigNotInitialized`
/// - IO 错误时返回 `ApiErrorCode::Internal`
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
/// let config = api::get_backend_config().unwrap();
/// println!("HTTP 服务: {}", config.http_enabled);
/// ```
Future<BackendConfigDto> getBackendConfig() =>
    RustLib.instance.api.crateApiGetBackendConfig();

/// 更新后端服务配置
///
/// 更新并保存后端接口（HTTP/MCP/CLI）的启用状态配置。
///
/// # 参数
/// * `http_enabled` - 是否启用 HTTP 服务接口
/// * `mcp_enabled` - 是否启用 MCP（Model Context Protocol）服务接口
/// * `cli_enabled` - 是否启用 CLI 命令行接口
///
/// # 返回
/// - `Ok(BackendConfigDto)` - 更新后的配置
/// - `Err(ApiError)` - 配置保存失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::IoError` - 配置文件读写失败
/// - `ApiErrorCode::Internal` - 内部错误（锁被 poison）
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// // 启用 HTTP 和 MCP，禁用 CLI
/// let config = api::update_backend_config(true, true, false).unwrap();
/// assert!(config.http_enabled);
/// assert!(config.mcp_enabled);
/// assert!(!config.cli_enabled);
/// ```
Future<BackendConfigDto> updateBackendConfig({
  required bool httpEnabled,
  required bool mcpEnabled,
  required bool cliEnabled,
}) => RustLib.instance.api.crateApiUpdateBackendConfig(
  httpEnabled: httpEnabled,
  mcpEnabled: mcpEnabled,
  cliEnabled: cliEnabled,
);

/// 获取运行时入口状态
///
/// 查询当前后端服务的运行时入口状态，包括各接口（HTTP/MCP/CLI）的启动状态、
/// 监听地址、连接数等信息。
///
/// # 返回
/// - `Ok(RuntimeEntryStatusDto)` - 运行时入口状态详情
/// - `Err(ApiError)` - 查询失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let status = api::get_runtime_entry_status().unwrap();
/// println!("HTTP 监听: {:?}", status.http_bind_addr);
/// println!("MCP 监听: {:?}", status.mcp_bind_addr);
/// println!("CLI 启用: {}", status.cli_enabled);
/// ```
Future<RuntimeEntryStatusDto> getRuntimeEntryStatus() =>
    RustLib.instance.api.crateApiGetRuntimeEntryStatus();

/// 初始化应用级配置
///
/// 必须在调用任何其他 API 之前执行。设置全局应用数据目录，初始化存储目录结构。
///
/// # Arguments
/// * `app_data_dir` - 应用数据根目录的绝对路径（如 `/Users/xxx/Library/Application Support/com.example.app`）
///
/// # Returns
/// - `Ok(())` - 初始化成功
/// - `Err(ApiError)` - 目录创建失败或已被其他路径初始化
///
/// # Panics
/// - 锁 poison 时返回 `ApiErrorCode::Internal`
/// - 已用不同路径初始化时返回 `ApiErrorCode::AppConfigConflict`
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// // 首次初始化
/// let result = api::init_app_config("/path/to/data".to_string());
/// assert!(result.is_ok());
///
/// // 重复初始化相同路径（幂等）
/// let result = api::init_app_config("/path/to/data".to_string());
/// assert!(result.is_ok()); // 不会报错
///
/// // 用不同路径初始化（报错）
/// let result = api::init_app_config("/different/path".to_string());
/// assert!(result.is_err()); // AppConfigConflict
/// ```
Future<void> initAppConfig({required String appDataDir}) =>
    RustLib.instance.api.crateApiInitAppConfig(appDataDir: appDataDir);

/// 重置应用配置（测试用）
///
/// 清除已初始化的应用配置，将全局配置状态重置为未初始化。
/// 仅用于测试场景，生产代码不应调用此函数。
///
/// # Returns
/// - `Ok(())` - 重置成功
/// - `Err(ApiError)` - 重置失败
///
/// # Errors
/// - `ApiErrorCode::Internal` - 锁被 poison
Future<void> resetAppConfigForTests() =>
    RustLib.instance.api.crateApiResetAppConfigForTests();

Future<(bool, bool)> appLockStatus() =>
    RustLib.instance.api.crateApiAppLockStatus();

Future<void> setupAppLock({
  required String pin,
  required bool allowBiometric,
}) => RustLib.instance.api.crateApiSetupAppLock(
  pin: pin,
  allowBiometric: allowBiometric,
);

Future<void> verifyAppLockWithPin({required String pin}) =>
    RustLib.instance.api.crateApiVerifyAppLockWithPin(pin: pin);

Future<void> markBiometricSuccess() =>
    RustLib.instance.api.crateApiMarkBiometricSuccess();

Future<void> resetAppLockForTests() =>
    RustLib.instance.api.crateApiResetAppLockForTests();

/// 创建新的数据池
///
/// 创建一个新的 Pool（数据池），当前设备作为管理员加入。
///
/// # Arguments
/// * `endpoint_id` - 当前设备的唯一标识符（建议使用设备 UUID）
/// * `nickname` - 成员在池中的显示名称
/// * `os` - 操作系统标识（如 "macOS", "Windows", "Linux"）
///
/// # Returns
/// - `Ok(PoolDto)` - 创建成功的池信息，包含池 ID、名称、成员数等
/// - `Err(ApiError)` - 创建失败，可能原因：存储错误、参数无效
///
/// # Panics
/// - 应用配置未初始化时返回 `ApiErrorCode::AppConfigNotInitialized`
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let pool = api::create_pool(
///     "device-uuid-123".to_string(),
///     "我的工作池".to_string(),
///     "macOS".to_string(),
/// ).unwrap();
///
/// println!("池 ID: {}", pool.id);
/// println!("我的角色: {}", pool.current_user_role); // "admin"
/// ```
Future<PoolDto> createPool({
  required String endpointId,
  required String nickname,
  required String os,
}) => RustLib.instance.api.crateApiCreatePool(
  endpointId: endpointId,
  nickname: nickname,
  os: os,
);

/// 加入数据池
///
/// 作为新成员加入指定的数据池。加入后将同步池中已有的卡片引用。
///
/// # 参数
/// * `pool_id` - 要加入的数据池 ID（UUID 字符串）
/// * `endpoint_id` - 当前设备的唯一标识符
/// * `nickname` - 成员在池中的显示名称
/// * `os` - 操作系统标识（如 "macOS", "Windows", "Linux"）
///
/// # 返回
/// - `Ok(PoolDto)` - 加入成功后的池信息
/// - `Err(ApiError)` - 加入失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidArgument` - 无效的 pool_id 格式
/// - `ApiErrorCode::PoolNotFound` - 指定的池不存在
/// - `ApiErrorCode::AlreadyMember` - 已经是该池的成员
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// // 加入现有池
/// let pool = api::join_pool(
///     "pool-uuid-123".to_string(),
///     "device-uuid-456".to_string(),
///     "Bob".to_string(),
///     "Windows".to_string(),
/// ).unwrap();
///
/// println!("已加入池: {}", pool.name);
/// println!("我的角色: {}", pool.current_user_role);
/// ```
Future<PoolDto> joinPool({
  required String poolId,
  required String endpointId,
  required String nickname,
  required String os,
}) => RustLib.instance.api.crateApiJoinPool(
  poolId: poolId,
  endpointId: endpointId,
  nickname: nickname,
  os: os,
);

/// 通过加入码加入数据池
///
/// 使用加入码（Join Code）加入数据池。加入码通常由池管理员生成并分享。
///
/// # 参数
/// * `code` - 加入码字符串
/// * `endpoint_id` - 当前设备的唯一标识符
/// * `nickname` - 成员在池中的显示名称
/// * `os` - 操作系统标识
///
/// # 返回
/// - `Ok(PoolDto)` - 加入成功后的池信息
/// - `Err(ApiError)` - 加入失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidPoolHash` - 无效的加入码
/// - `ApiErrorCode::PoolNotFound` - 加入码对应的池不存在
/// - `ApiErrorCode::RequestTimeout` - 加入请求超时
/// - `ApiErrorCode::AlreadyMember` - 已经是该池的成员
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// // 通过加入码加入
/// let pool = api::join_by_code(
///     "ABC123XYZ".to_string(),
///     "device-uuid-789".to_string(),
///     "Charlie".to_string(),
///     "Linux".to_string(),
/// ).unwrap();
///
/// println!("成功加入池: {}", pool.name);
/// ```
Future<PoolDto> joinByCode({
  required String code,
  required String endpointId,
  required String nickname,
  required String os,
}) => RustLib.instance.api.crateApiJoinByCode(
  code: code,
  endpointId: endpointId,
  nickname: nickname,
  os: os,
);

/// 离开数据池
///
/// 从指定数据池中移除当前 endpoint 对应的成员关系。
Future<PoolDto> leavePool({
  required String poolId,
  required String endpointId,
}) => RustLib.instance.api.crateApiLeavePool(
  poolId: poolId,
  endpointId: endpointId,
);

/// 解散数据池
Future<PoolDto> dissolvePool({
  required String poolId,
  required String endpointId,
}) => RustLib.instance.api.crateApiDissolvePool(
  poolId: poolId,
  endpointId: endpointId,
);

Future<List<JoinRequestDto>> submitJoinRequest({
  required String poolId,
  required String endpointId,
  required String nickname,
  required String os,
}) => RustLib.instance.api.crateApiSubmitJoinRequest(
  poolId: poolId,
  endpointId: endpointId,
  nickname: nickname,
  os: os,
);

Future<List<JoinRequestDto>> approveJoinRequest({
  required String poolId,
  required String requestId,
  required String approverEndpointId,
}) => RustLib.instance.api.crateApiApproveJoinRequest(
  poolId: poolId,
  requestId: requestId,
  approverEndpointId: approverEndpointId,
);

Future<List<JoinRequestDto>> rejectJoinRequest({
  required String poolId,
  required String requestId,
  required String approverEndpointId,
}) => RustLib.instance.api.crateApiRejectJoinRequest(
  poolId: poolId,
  requestId: requestId,
  approverEndpointId: approverEndpointId,
);

Future<List<JoinRequestDto>> cancelJoinRequest({
  required String poolId,
  required String requestId,
  required String applicantEndpointId,
}) => RustLib.instance.api.crateApiCancelJoinRequest(
  poolId: poolId,
  requestId: requestId,
  applicantEndpointId: applicantEndpointId,
);

/// 列出所有数据池
///
/// 获取当前设备关联的所有数据池列表。目前实现返回单个池或空列表。
///
/// # 参数
/// * `endpoint_id` - 当前设备的唯一标识符
///
/// # 返回
/// - `Ok(Vec<PoolDto>)` - 数据池列表（可能为空）
/// - `Err(ApiError)` - 查询失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let pools = api::list_pools("device-uuid-001".to_string()).unwrap();
/// for pool in pools {
///     println!("池: {} (角色: {})", pool.name, pool.current_user_role);
/// }
/// ```
Future<List<PoolDto>> listPools({required String endpointId}) =>
    RustLib.instance.api.crateApiListPools(endpointId: endpointId);

/// 获取数据池详情
///
/// 获取指定数据池的详细信息，包括成员列表、卡片 ID 列表等。
///
/// # 参数
/// * `pool_id` - 数据池 ID（UUID 字符串）
/// * `endpoint_id` - 当前设备的唯一标识符
///
/// # 返回
/// - `Ok(PoolDetailDto)` - 数据池详细信息
/// - `Err(ApiError)` - 查询失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidArgument` - 无效的 pool_id 格式
/// - `ApiErrorCode::PoolNotFound` - 指定的池不存在
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let detail = api::get_pool_detail(
///     "pool-uuid-123".to_string(),
///     "device-uuid-001".to_string(),
/// ).unwrap();
///
/// println!("池名称: {}", detail.name);
/// println!("成员数: {}", detail.member_count);
/// println!("卡片数: {}", detail.note_ids.len());
/// ```
Future<PoolDetailDto> getPoolDetail({
  required String poolId,
  required String endpointId,
}) => RustLib.instance.api.crateApiGetPoolDetail(
  poolId: poolId,
  endpointId: endpointId,
);

/// 获取已加入的数据池视图
///
/// 获取当前设备已加入的数据池的详细信息。如果设备未加入任何池则返回错误。
///
/// # 参数
/// * `endpoint_id` - 当前设备的唯一标识符
///
/// # 返回
/// - `Ok(PoolDetailDto)` - 已加入池的详细信息
/// - `Err(ApiError)` - 查询失败（未加入任何池）
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::NotFound` - 当前设备未加入任何数据池
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// match api::get_joined_pool_view("device-uuid-001".to_string()) {
///     Ok(detail) => println!("已加入池: {}", detail.name),
///     Err(e) => println!("未加入任何池: {:?}", e),
/// }
/// ```
Future<PoolDetailDto> getJoinedPoolView({required String endpointId}) =>
    RustLib.instance.api.crateApiGetJoinedPoolView(endpointId: endpointId);

/// 创建卡片笔记
///
/// 创建一个新的卡片笔记，包含标题和内容。
///
/// # 参数
/// * `title` - 卡片标题
/// * `content` - 卡片内容（支持 Markdown 格式）
///
/// # 返回
/// - `Ok(CardNoteDto)` - 创建成功的卡片信息
/// - `Err(ApiError)` - 创建失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let card = api::create_card_note(
///     "Rust 所有权".to_string(),
///     "所有权是 Rust 的核心特性...".to_string(),
/// ).unwrap();
///
/// println!("创建卡片 ID: {}", card.id);
/// println!("创建时间: {}", card.created_at);
/// ```
Future<CardNoteDto> createCardNote({
  required String title,
  required String content,
}) =>
    RustLib.instance.api.crateApiCreateCardNote(title: title, content: content);

/// 在指定池中创建卡片
///
/// 创建卡片笔记并将其关联到指定的数据池。
///
/// # 参数
/// * `pool_id` - 数据池 ID（UUID 字符串）
/// * `title` - 卡片标题
/// * `content` - 卡片内容
///
/// # 返回
/// - `Ok(CardNoteDto)` - 创建成功的卡片信息
/// - `Err(ApiError)` - 创建失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidArgument` - 无效的 pool_id 格式
/// - `ApiErrorCode::PoolNotFound` - 指定的池不存在
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let card = api::create_card_note_in_pool(
///     "pool-uuid-123".to_string(),
///     "会议记录".to_string(),
///     "今天讨论了...".to_string(),
/// ).unwrap();
///
/// println!("在池中创建卡片: {}", card.title);
/// ```
Future<CardNoteDto> createCardNoteInPool({
  required String poolId,
  required String title,
  required String content,
}) => RustLib.instance.api.crateApiCreateCardNoteInPool(
  poolId: poolId,
  title: title,
  content: content,
);

/// 更新卡片笔记
///
/// 更新指定卡片的标题和内容。
///
/// # 参数
/// * `card_id` - 卡片 ID（UUID 字符串）
/// * `title` - 新的卡片标题
/// * `content` - 新的卡片内容
///
/// # 返回
/// - `Ok(CardNoteDto)` - 更新后的卡片信息
/// - `Err(ApiError)` - 更新失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidArgument` - 无效的 card_id 格式
/// - `ApiErrorCode::NotFound` - 指定的卡片不存在
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let updated = api::update_card_note(
///     "card-uuid-456".to_string(),
///     "更新后的标题".to_string(),
///     "更新后的内容...".to_string(),
/// ).unwrap();
///
/// println!("更新时间: {}", updated.updated_at);
/// ```
Future<CardNoteDto> updateCardNote({
  required String cardId,
  required String title,
  required String content,
}) => RustLib.instance.api.crateApiUpdateCardNote(
  cardId: cardId,
  title: title,
  content: content,
);

/// 删除卡片笔记（软删除）
///
/// 将指定卡片标记为已删除（软删除），卡片数据仍然保留但不再显示在列表中。
/// 可以使用 [`restore_card_note`] 恢复已删除的卡片。
///
/// # 参数
/// * `card_id` - 要删除的卡片 ID（UUID 字符串）
///
/// # 返回
/// - `Ok(CardNoteDto)` - 删除后的卡片信息（deleted 字段为 true）
/// - `Err(ApiError)` - 删除失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidArgument` - 无效的 card_id 格式
/// - `ApiErrorCode::NotFound` - 指定的卡片不存在
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let deleted = api::delete_card_note("card-uuid-456".to_string()).unwrap();
/// assert!(deleted.deleted);
///
/// // 稍后可以通过 restore_card_note 恢复
/// let restored = api::restore_card_note("card-uuid-456".to_string()).unwrap();
/// assert!(!restored.deleted);
/// ```
Future<CardNoteDto> deleteCardNote({required String cardId}) =>
    RustLib.instance.api.crateApiDeleteCardNote(cardId: cardId);

/// 恢复已删除的卡片
///
/// 恢复被软删除的卡片，使其重新在列表中显示。
///
/// # 参数
/// * `card_id` - 要恢复的卡片 ID（UUID 字符串）
///
/// # 返回
/// - `Ok(CardNoteDto)` - 恢复后的卡片信息（deleted 字段为 false）
/// - `Err(ApiError)` - 恢复失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidArgument` - 无效的 card_id 格式
/// - `ApiErrorCode::NotFound` - 指定的卡片不存在
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// // 先删除再恢复
/// let _ = api::delete_card_note("card-uuid-456".to_string()).unwrap();
/// let restored = api::restore_card_note("card-uuid-456".to_string()).unwrap();
///
/// assert!(!restored.deleted);
/// println!("卡片已恢复: {}", restored.title);
/// ```
Future<CardNoteDto> restoreCardNote({required String cardId}) =>
    RustLib.instance.api.crateApiRestoreCardNote(cardId: cardId);

/// 列出所有卡片
///
/// 获取所有卡片的列表（不包括已删除的卡片）。
///
/// # 返回
/// - `Ok(Vec<CardNoteDto>)` - 卡片列表
/// - `Err(ApiError)` - 查询失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let cards = api::list_card_notes().unwrap();
/// println!("共有 {} 张卡片", cards.len());
///
/// for card in cards {
///     println!("- {}: {}", card.id, card.title);
/// }
/// ```
Future<List<CardNoteDto>> listCardNotes() =>
    RustLib.instance.api.crateApiListCardNotes();

/// 查询卡片
///
/// 根据查询条件搜索卡片，支持全文搜索标题和内容。
///
/// # 参数
/// * `query` - 搜索关键词（在标题和内容中搜索）
/// * `pool_id` - 可选，限制在指定池中搜索
/// * `include_deleted` - 可选，是否包含已删除的卡片（默认 false）
///
/// # 返回
/// - `Ok(Vec<CardNoteDto>)` - 匹配的卡片列表
/// - `Err(ApiError)` - 查询失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// // 搜索包含 "Rust" 的卡片
/// let results = api::query_card_notes(
///     "Rust".to_string(),
///     None,
///     Some(false),
/// ).unwrap();
///
/// // 在特定池中搜索
/// let pool_results = api::query_card_notes(
///     "会议".to_string(),
///     Some("pool-uuid-123".to_string()),
///     None,
/// ).unwrap();
/// ```
Future<List<CardNoteDto>> queryCardNotes({
  required String query,
  String? poolId,
  bool? includeDeleted,
}) => RustLib.instance.api.crateApiQueryCardNotes(
  query: query,
  poolId: poolId,
  includeDeleted: includeDeleted,
);

/// 获取卡片详情
///
/// 获取指定卡片的完整信息。
///
/// # 参数
/// * `card_id` - 卡片 ID（UUID 字符串）
///
/// # 返回
/// - `Ok(CardNoteDto)` - 卡片详细信息
/// - `Err(ApiError)` - 查询失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::AppConfigNotInitialized` - 应用配置未初始化
/// - `ApiErrorCode::InvalidArgument` - 无效的 card_id 格式
/// - `ApiErrorCode::NotFound` - 指定的卡片不存在
/// - `ApiErrorCode::SqliteError` - 数据库操作失败
/// - `ApiErrorCode::Internal` - 内部错误
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
///
/// let card = api::get_card_note_detail("card-uuid-456".to_string()).unwrap();
/// println!("标题: {}", card.title);
/// println!("内容: {}", card.content);
/// println!("创建时间: {}", card.created_at);
/// ```
Future<CardNoteDto> getCardNoteDetail({required String cardId}) =>
    RustLib.instance.api.crateApiGetCardNoteDetail(cardId: cardId);

/// 初始化 PoolNetwork 网络层
///
/// 创建一个新的 P2P 网络实例，包含独立的 Tokio 运行时、QUIC 端点与存储句柄。
/// 每个网络实例通过递增的 `network_id` 唯一标识。
///
/// # Arguments
/// * `base_path` - 数据存储根目录路径（应与应用配置路径一致）
///
/// # Returns
/// - `Ok(u64)` - 网络实例的唯一标识符，用于后续网络操作
/// - `Err(ApiError)` - 初始化失败，可能原因：端口占用、存储错误
///
/// # Safety
/// - 每个 PoolNetwork 拥有独立的 Tokio 运行时（`new_current_thread` 模式）
/// - 运行时在线程内创建，与 FFI 调用线程绑定
/// - 不跨线程共享运行时，避免 `Send` 约束问题
///
/// # Panics
/// - Tokio 运行时创建失败时返回 `ApiErrorCode::Internal`
/// - 存储初始化失败时返回相应的存储错误码
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// // 初始化网络和存储
/// api::init_app_config("/data".to_string()).unwrap();
///
/// // 创建网络实例
/// let network_id = api::init_pool_network("/data".to_string()).unwrap();
///
/// // 连接到其他设备
/// api::sync_connect(network_id, "192.168.1.100:8080".to_string()).unwrap();
///
/// // 关闭网络
/// api::close_pool_network(network_id).unwrap();
/// ```
Future<BigInt> initPoolNetwork({required String basePath}) =>
    RustLib.instance.api.crateApiInitPoolNetwork(basePath: basePath);

/// 获取网络实例当前的 iroh 端点 ID。
Future<String> getPoolNetworkEndpointId({required BigInt networkId}) =>
    RustLib.instance.api.crateApiGetPoolNetworkEndpointId(networkId: networkId);

/// 获取网络实例当前可连接的同步目标地址。
Future<String> getPoolNetworkSyncTarget({required BigInt networkId}) =>
    RustLib.instance.api.crateApiGetPoolNetworkSyncTarget(networkId: networkId);

/// 为指定池生成可分享的邀请字符串。
Future<String> createPoolInvite({
  required BigInt networkId,
  required String poolId,
}) => RustLib.instance.api.crateApiCreatePoolInvite(
  networkId: networkId,
  poolId: poolId,
);

/// 通过邀请字符串加入池并拉取完整快照。
Future<JoinByInviteResultDto> joinPoolByInvite({
  required BigInt networkId,
  required String code,
  required String nickname,
  required String os,
  required bool debugTrace,
}) => RustLib.instance.api.crateApiJoinPoolByInvite(
  networkId: networkId,
  code: code,
  nickname: nickname,
  os: os,
  debugTrace: debugTrace,
);

Future<PoolMembersRuntimeViewDto> getPoolMembersRuntimeView({
  required String poolId,
  required String endpointId,
}) => RustLib.instance.api.crateApiGetPoolMembersRuntimeView(
  poolId: poolId,
  endpointId: endpointId,
);

Future<PoolRuntimeSummaryDto> getPoolRuntimeSummary({
  required String poolId,
  required String endpointId,
}) => RustLib.instance.api.crateApiGetPoolRuntimeSummary(
  poolId: poolId,
  endpointId: endpointId,
);

Future<PoolInvitesViewDto> listActiveInvites({
  required String poolId,
  required String endpointId,
}) => RustLib.instance.api.crateApiListActiveInvites(
  poolId: poolId,
  endpointId: endpointId,
);

Future<PoolInvitesViewDto> revokeInvite({
  required String poolId,
  required String inviteId,
  required String endpointId,
}) => RustLib.instance.api.crateApiRevokeInvite(
  poolId: poolId,
  inviteId: inviteId,
  endpointId: endpointId,
);

/// 关闭 PoolNetwork 网络实例
///
/// 停止指定网络实例，释放相关资源（连接、运行时等）。
/// 关闭后该 `network_id` 将失效，不能再用于其他网络操作。
///
/// # Arguments
/// * `network_id` - 要关闭的网络实例 ID（由 [`init_pool_network`] 返回）
///
/// # Returns
/// - `Ok(())` - 关闭成功
/// - `Err(ApiError)` - 网络实例不存在（`ApiErrorCode::NotFound`）
///
/// # Panics
/// - 锁 poison 时返回 `ApiErrorCode::Internal`
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// let network_id = api::init_pool_network("/data".to_string()).unwrap();
///
/// // ... 进行网络操作 ...
///
/// // 关闭网络
/// api::close_pool_network(network_id).unwrap();
///
/// // 再次关闭会报错
/// let result = api::close_pool_network(network_id);
/// assert!(result.is_err()); // NotFound
/// ```
Future<void> closePoolNetwork({required BigInt networkId}) =>
    RustLib.instance.api.crateApiClosePoolNetwork(networkId: networkId);

Future<void> closeAllPoolNetworksForTests() =>
    RustLib.instance.api.crateApiCloseAllPoolNetworksForTests();

/// 获取同步状态
///
/// 查询指定网络实例的当前同步状态，包括连接状态、数据一致性状态等。
///
/// # 参数
/// * `network_id` - 网络实例 ID（由 [`init_pool_network`] 返回）
///
/// # 返回
/// - `Ok(SyncStatusDto)` - 详细的同步状态信息
/// - `Err(ApiError)` - 查询失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::Internal` - 内部错误（锁被 poison）
/// - `ApiErrorCode::InvalidHandle` - 无效的网络实例 ID
/// - `ApiErrorCode::ProjectionNotConverged` - 投影尚未收敛
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
/// let network_id = api::init_pool_network("/data".to_string()).unwrap();
///
/// let status = api::sync_status(network_id).unwrap();
/// println!("同步状态: {}", status.sync_state);
/// println!("查询收敛: {}", status.query_convergence_state);
/// println!("允许的操作: {:?}", status.allowed_operations);
/// ```
Future<SyncStatusDto> syncStatus({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncStatus(networkId: networkId);

/// 建立同步连接。
///
/// 连接到目标节点以开始数据同步。
///
/// # 参数
/// * `network_id` - 网络实例 ID（由 [`init_pool_network`] 返回）
/// * `target` - 目标节点地址
///
/// # 返回
/// - `Ok(())` - 连接成功
/// - `Err(ApiError)` - 连接失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::Internal` - 内部错误（锁被 poison）
/// - `ApiErrorCode::InvalidHandle` - 无效的网络实例 ID
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// let network_id = api::init_pool_network("owner".to_string(), "Owner".to_string(), "macOS".to_string()).unwrap();
/// api::sync_connect(network_id, "peer-address".to_string()).unwrap();
/// ```
Future<void> syncConnect({required BigInt networkId, required String target}) =>
    RustLib.instance.api.crateApiSyncConnect(
      networkId: networkId,
      target: target,
    );

/// 断开同步连接
///
/// 断开指定网络实例的同步连接，停止与其他设备的同步。
///
/// # 参数
/// * `network_id` - 网络实例 ID（由 [`init_pool_network`] 返回）
///
/// # 返回
/// - `Ok(())` - 断开成功
/// - `Err(ApiError)` - 断开失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::Internal` - 内部错误（锁被 poison）
/// - `ApiErrorCode::InvalidHandle` - 无效的网络实例 ID
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
/// let network_id = api::init_pool_network("/data".to_string()).unwrap();
///
/// // 连接后断开
/// api::sync_connect(network_id, "192.168.1.100:8080".to_string()).unwrap();
/// api::sync_disconnect(network_id).unwrap();
/// println!("同步已断开");
/// ```
Future<void> syncDisconnect({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncDisconnect(networkId: networkId);

/// 在同步会话中加入池
///
/// 在指定的网络同步会话中加入数据池，建立池级别的同步上下文。
///
/// # 参数
/// * `network_id` - 网络实例 ID（由 [`init_pool_network`] 返回）
/// * `pool_id` - 要加入的数据池 ID（UUID 字符串）
///
/// # 返回
/// - `Ok(())` - 加入成功
/// - `Err(ApiError)` - 加入失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::Internal` - 内部错误（锁被 poison）
/// - `ApiErrorCode::InvalidHandle` - 无效的网络实例 ID
/// - `ApiErrorCode::InvalidArgument` - 无效的 pool_id 格式
/// - `ApiErrorCode::PoolNotFound` - 指定的池不存在
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
/// let network_id = api::init_pool_network("/data".to_string()).unwrap();
///
/// // 在同步会话中加入池
/// api::sync_join_pool(network_id, "pool-uuid-123".to_string()).unwrap();
/// println!("已在同步会话中加入池");
/// ```
Future<void> syncJoinPool({
  required BigInt networkId,
  required String poolId,
}) => RustLib.instance.api.crateApiSyncJoinPool(
  networkId: networkId,
  poolId: poolId,
);

/// 推送同步数据
///
/// 将本地数据推送到同步网络，与其他设备同步。
///
/// # 参数
/// * `network_id` - 网络实例 ID（由 [`init_pool_network`] 返回）
///
/// # 返回
/// - `Ok(SyncResultDto)` - 同步操作结果
/// - `Err(ApiError)` - 同步失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::Internal` - 内部错误（锁被 poison）
/// - `ApiErrorCode::InvalidHandle` - 无效的网络实例 ID
/// - `ApiErrorCode::RequestTimeout` - 同步未连接或超时
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
/// let network_id = api::init_pool_network("/data".to_string()).unwrap();
///
/// // 连接并推送
/// api::sync_connect(network_id, "192.168.1.100:8080".to_string()).unwrap();
/// let result = api::sync_push(network_id).unwrap();
///
/// println!("同步状态: {}", result.sync_state);
/// println!("下一步操作: {}", result.next_action);
/// ```
Future<SyncResultDto> syncPush({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncPush(networkId: networkId);

/// 拉取同步数据
///
/// 从同步网络拉取其他设备的更新数据到本地。
///
/// # 参数
/// * `network_id` - 网络实例 ID（由 [`init_pool_network`] 返回）
///
/// # 返回
/// - `Ok(SyncResultDto)` - 同步操作结果
/// - `Err(ApiError)` - 同步失败
///
/// # Errors
/// 可能返回的错误码：
/// - `ApiErrorCode::Internal` - 内部错误（锁被 poison）
/// - `ApiErrorCode::InvalidHandle` - 无效的网络实例 ID
/// - `ApiErrorCode::RequestTimeout` - 同步未连接或超时
///
/// # Examples
/// ```rust,ignore
/// use cardmind_rust::api;
///
/// api::init_app_config("/data".to_string()).unwrap();
/// let network_id = api::init_pool_network("/data".to_string()).unwrap();
///
/// // 连接并拉取
/// api::sync_connect(network_id, "192.168.1.100:8080".to_string()).unwrap();
/// let result = api::sync_pull(network_id).unwrap();
///
/// println!("同步状态: {}", result.sync_state);
/// println!("实例连续性: {}", result.instance_continuity_state);
/// ```
Future<SyncResultDto> syncPull({required BigInt networkId}) =>
    RustLib.instance.api.crateApiSyncPull(networkId: networkId);

/// 卡片笔记 DTO。
///
/// 用于前后端数据传输，包含笔记的完整内容。
class CardNoteDto {
  final String id;
  final String title;
  final String content;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final bool deleted;

  const CardNoteDto({
    required this.id,
    required this.title,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
    required this.deleted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardNoteDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          content == other.content &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deleted == other.deleted;
}

class JoinByInviteResultDto {
  final String status;
  final String poolId;
  final String poolName;
  final String? requestId;

  const JoinByInviteResultDto({
    required this.status,
    required this.poolId,
    required this.poolName,
    this.requestId,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      poolId.hashCode ^
      poolName.hashCode ^
      requestId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JoinByInviteResultDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          poolId == other.poolId &&
          poolName == other.poolName &&
          requestId == other.requestId;
}

class JoinRequestDto {
  final String requestId;
  final String applicantEndpointId;
  final String applicantNickname;
  final String applicantOs;
  final String status;

  const JoinRequestDto({
    required this.requestId,
    required this.applicantEndpointId,
    required this.applicantNickname,
    required this.applicantOs,
    required this.status,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      applicantEndpointId.hashCode ^
      applicantNickname.hashCode ^
      applicantOs.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JoinRequestDto &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          applicantEndpointId == other.applicantEndpointId &&
          applicantNickname == other.applicantNickname &&
          applicantOs == other.applicantOs &&
          status == other.status;
}

/// 数据池详细信息 DTO。
///
/// 包含池的完整信息，包括成员列表和笔记 ID 列表。
class PoolDetailDto {
  final String id;
  final String name;
  final bool isDissolved;
  final String currentUserRole;
  final BigInt memberCount;
  final List<String> noteIds;
  final List<PoolMemberDto> members;
  final List<JoinRequestDto> joinRequests;

  const PoolDetailDto({
    required this.id,
    required this.name,
    required this.isDissolved,
    required this.currentUserRole,
    required this.memberCount,
    required this.noteIds,
    required this.members,
    required this.joinRequests,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isDissolved.hashCode ^
      currentUserRole.hashCode ^
      memberCount.hashCode ^
      noteIds.hashCode ^
      members.hashCode ^
      joinRequests.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDissolved == other.isDissolved &&
          currentUserRole == other.currentUserRole &&
          memberCount == other.memberCount &&
          noteIds == other.noteIds &&
          members == other.members &&
          joinRequests == other.joinRequests;
}

/// 数据池信息 DTO。
///
/// 用于前后端数据传输，展示池的基本信息。
class PoolDto {
  final String id;
  final String name;
  final bool isDissolved;
  final String currentUserRole;
  final BigInt memberCount;

  const PoolDto({
    required this.id,
    required this.name,
    required this.isDissolved,
    required this.currentUserRole,
    required this.memberCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isDissolved.hashCode ^
      currentUserRole.hashCode ^
      memberCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDissolved == other.isDissolved &&
          currentUserRole == other.currentUserRole &&
          memberCount == other.memberCount;
}

class PoolInviteDto {
  final String inviteId;
  final String inviteCode;
  final String createdByEndpointId;
  final PlatformInt64 createdAt;

  const PoolInviteDto({
    required this.inviteId,
    required this.inviteCode,
    required this.createdByEndpointId,
    required this.createdAt,
  });

  static Future<PoolInviteDto> fromRecord({required PoolInviteRecord record}) =>
      RustLib.instance.api.crateApiPoolInviteDtoFromRecord(record: record);

  @override
  int get hashCode =>
      inviteId.hashCode ^
      inviteCode.hashCode ^
      createdByEndpointId.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolInviteDto &&
          runtimeType == other.runtimeType &&
          inviteId == other.inviteId &&
          inviteCode == other.inviteCode &&
          createdByEndpointId == other.createdByEndpointId &&
          createdAt == other.createdAt;
}

class PoolInvitesViewDto {
  final List<PoolInviteDto> invites;
  final BigInt activeCount;

  const PoolInvitesViewDto({required this.invites, required this.activeCount});

  static Future<PoolInvitesViewDto> fromRecords({
    required List<PoolInviteRecord> records,
  }) => RustLib.instance.api.crateApiPoolInvitesViewDtoFromRecords(
    records: records,
  );

  @override
  int get hashCode => invites.hashCode ^ activeCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolInvitesViewDto &&
          runtimeType == other.runtimeType &&
          invites == other.invites &&
          activeCount == other.activeCount;
}

/// 池成员信息 DTO。
///
/// 描述数据池中的成员基本信息。
class PoolMemberDto {
  final String endpointId;
  final String nickname;
  final String os;
  final String role;

  const PoolMemberDto({
    required this.endpointId,
    required this.nickname,
    required this.os,
    required this.role,
  });

  @override
  int get hashCode =>
      endpointId.hashCode ^ nickname.hashCode ^ os.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolMemberDto &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          nickname == other.nickname &&
          os == other.os &&
          role == other.role;
}

class PoolMemberRuntimeDto {
  final String endpointId;
  final String nickname;
  final String os;
  final String role;
  final String status;
  final PlatformInt64? lastActiveAt;
  final bool isCurrentDevice;

  const PoolMemberRuntimeDto({
    required this.endpointId,
    required this.nickname,
    required this.os,
    required this.role,
    required this.status,
    this.lastActiveAt,
    required this.isCurrentDevice,
  });

  static Future<PoolMemberRuntimeDto> fromRuntime({
    required PoolMemberRuntime runtime,
  }) => RustLib.instance.api.crateApiPoolMemberRuntimeDtoFromRuntime(
    runtime: runtime,
  );

  @override
  int get hashCode =>
      endpointId.hashCode ^
      nickname.hashCode ^
      os.hashCode ^
      role.hashCode ^
      status.hashCode ^
      lastActiveAt.hashCode ^
      isCurrentDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolMemberRuntimeDto &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          nickname == other.nickname &&
          os == other.os &&
          role == other.role &&
          status == other.status &&
          lastActiveAt == other.lastActiveAt &&
          isCurrentDevice == other.isCurrentDevice;
}

class PoolMembersRuntimeViewDto {
  final List<PoolMemberRuntimeDto> rows;

  const PoolMembersRuntimeViewDto({required this.rows});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PoolMembersRuntimeViewDto> newInstance({
    required List<PoolMemberRuntimeDto> rows,
  }) => RustLib.instance.api.crateApiPoolMembersRuntimeViewDtoNew(rows: rows);

  @override
  int get hashCode => rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolMembersRuntimeViewDto &&
          runtimeType == other.runtimeType &&
          rows == other.rows;
}

class PoolRuntimeSummaryDto {
  final BigInt memberCount;
  final BigInt connectedCount;
  final BigInt syncingCount;
  final BigInt offlineCount;
  final String memberCountText;
  final String runtimeStatusText;

  const PoolRuntimeSummaryDto({
    required this.memberCount,
    required this.connectedCount,
    required this.syncingCount,
    required this.offlineCount,
    required this.memberCountText,
    required this.runtimeStatusText,
  });

  static Future<PoolRuntimeSummaryDto> fromCounts({
    required BigInt memberCount,
    required BigInt connectedCount,
    required BigInt syncingCount,
    required BigInt offlineCount,
  }) => RustLib.instance.api.crateApiPoolRuntimeSummaryDtoFromCounts(
    memberCount: memberCount,
    connectedCount: connectedCount,
    syncingCount: syncingCount,
    offlineCount: offlineCount,
  );

  static Future<PoolRuntimeSummaryDto> fromSummary({
    required PoolRuntimeSummary summary,
  }) => RustLib.instance.api.crateApiPoolRuntimeSummaryDtoFromSummary(
    summary: summary,
  );

  @override
  int get hashCode =>
      memberCount.hashCode ^
      connectedCount.hashCode ^
      syncingCount.hashCode ^
      offlineCount.hashCode ^
      memberCountText.hashCode ^
      runtimeStatusText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolRuntimeSummaryDto &&
          runtimeType == other.runtimeType &&
          memberCount == other.memberCount &&
          connectedCount == other.connectedCount &&
          syncingCount == other.syncingCount &&
          offlineCount == other.offlineCount &&
          memberCountText == other.memberCountText &&
          runtimeStatusText == other.runtimeStatusText;
}

/// 同步操作结果 DTO。
///
/// 描述同步操作的结果状态。
class SyncResultDto {
  final String syncState;
  final String queryConvergenceState;
  final String instanceContinuityState;
  final String localContentSafety;
  final String recoveryStage;
  final String continuityState;
  final String nextAction;
  final List<String> allowedOperations;
  final List<String> forbiddenOperations;
  final String? code;
  final String state;
  final String writeState;
  final String projectionState;
  final String contentState;

  const SyncResultDto({
    required this.syncState,
    required this.queryConvergenceState,
    required this.instanceContinuityState,
    required this.localContentSafety,
    required this.recoveryStage,
    required this.continuityState,
    required this.nextAction,
    required this.allowedOperations,
    required this.forbiddenOperations,
    this.code,
    required this.state,
    required this.writeState,
    required this.projectionState,
    required this.contentState,
  });

  @override
  int get hashCode =>
      syncState.hashCode ^
      queryConvergenceState.hashCode ^
      instanceContinuityState.hashCode ^
      localContentSafety.hashCode ^
      recoveryStage.hashCode ^
      continuityState.hashCode ^
      nextAction.hashCode ^
      allowedOperations.hashCode ^
      forbiddenOperations.hashCode ^
      code.hashCode ^
      state.hashCode ^
      writeState.hashCode ^
      projectionState.hashCode ^
      contentState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResultDto &&
          runtimeType == other.runtimeType &&
          syncState == other.syncState &&
          queryConvergenceState == other.queryConvergenceState &&
          instanceContinuityState == other.instanceContinuityState &&
          localContentSafety == other.localContentSafety &&
          recoveryStage == other.recoveryStage &&
          continuityState == other.continuityState &&
          nextAction == other.nextAction &&
          allowedOperations == other.allowedOperations &&
          forbiddenOperations == other.forbiddenOperations &&
          code == other.code &&
          state == other.state &&
          writeState == other.writeState &&
          projectionState == other.projectionState &&
          contentState == other.contentState;
}

/// 同步状态 DTO。
///
/// 描述当前同步状态，遵循 Phase 2 恢复契约。
class SyncStatusDto {
  final String syncState;
  final String queryConvergenceState;
  final String instanceContinuityState;
  final String localContentSafety;
  final String recoveryStage;
  final String continuityState;
  final String nextAction;
  final List<String> allowedOperations;
  final List<String> forbiddenOperations;
  final String? code;
  final String state;
  final String writeState;
  final String projectionState;
  final String contentState;

  const SyncStatusDto({
    required this.syncState,
    required this.queryConvergenceState,
    required this.instanceContinuityState,
    required this.localContentSafety,
    required this.recoveryStage,
    required this.continuityState,
    required this.nextAction,
    required this.allowedOperations,
    required this.forbiddenOperations,
    this.code,
    required this.state,
    required this.writeState,
    required this.projectionState,
    required this.contentState,
  });

  @override
  int get hashCode =>
      syncState.hashCode ^
      queryConvergenceState.hashCode ^
      instanceContinuityState.hashCode ^
      localContentSafety.hashCode ^
      recoveryStage.hashCode ^
      continuityState.hashCode ^
      nextAction.hashCode ^
      allowedOperations.hashCode ^
      forbiddenOperations.hashCode ^
      code.hashCode ^
      state.hashCode ^
      writeState.hashCode ^
      projectionState.hashCode ^
      contentState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          syncState == other.syncState &&
          queryConvergenceState == other.queryConvergenceState &&
          instanceContinuityState == other.instanceContinuityState &&
          localContentSafety == other.localContentSafety &&
          recoveryStage == other.recoveryStage &&
          continuityState == other.continuityState &&
          nextAction == other.nextAction &&
          allowedOperations == other.allowedOperations &&
          forbiddenOperations == other.forbiddenOperations &&
          code == other.code &&
          state == other.state &&
          writeState == other.writeState &&
          projectionState == other.projectionState &&
          contentState == other.contentState;
}
